### ISSUE TITLE
Indicate the cause of errors in the return value of osqp_setup

### ISSUE THREAD

**Issue by ebarnard** [oxfordcontrol/osqp#100]
Currently `osqp_setup` returns `NULL` on:
- Memory allocation failure
- Data validation failure
- Settings validation failure
- Solver dynamic library load failure
- Solver initialisation failure (including problem non-convexity)

It would be useful if the function returned an error code indicating the cause of the error as it is often desirable to disable output printing.

This would require changing the signature of `osqp_setup` to one of the following:

1. `int osqp_setup(OSQPWorkspace* work, const OSQPData *data, const OSQPSettings *settings)`
2. `int osqp_setup(OSQPWorkspace** work, const OSQPData *data, const OSQPSettings *settings)`
3. `OSQPWorkspace* osqp_setup(const OSQPData *data, const OSQPSettings *settings, int* status)`
where `status` contains an error code when the function return value is `NULL`.

I prefer option 1, unless there are plans to make OSQPWorkspace an opaque struct.

**Comment by bstellato** [comment]
It makes sense and I agree with option 1. We will add the return values in version `0.5.0`.

**Comment by bstellato** [comment]
This should be fixed in https://github.com/oxfordcontrol/osqp/pull/124. We need to update all the interfaces for that. The python one already works in the `develop` branch.

**Comment by ebarnard** [comment]
I've updated the rust interface ready for 0.6.0.

**Comment by gbanjac** [comment]
This is now added to release `0.6.0`.
