### ISSUE TITLE
osqp not able to find a feasible solution 

### ISSUE THREAD

**Issue by GiulioRomualdi** [oxfordcontrol/osqp#109]
I'm trying to solve a QP problem by using [`osqp-matlab`](https://github.com/oxfordcontrol/osqp-matlab) but seems the solver is not able to find a feasible solution. The outcome of the solver is `primal infeasibility`. 

The detailed output follows:
```
-----------------------------------------------------------------
           OSQP v0.4.1  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2018
-----------------------------------------------------------------
problem:  variables n = 64, constraints m = 82
          nnz(P) + nnz(A) = 1264
settings: linear system solver = qdldl,
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off

iter   objective    pri res    dua res    rho        time
   1  -1.1064e+01   3.24e+02   2.05e+05   1.00e-01   3.89e-04s
  50   1.0000e+20   1.07e+02   6.68e-02   1.00e-01   6.27e-04s

status:               primal infeasible
number of iterations: 50
run time:             6.45e-04s
optimal rho estimate: 9.14e-01
```

To understand if the cause of the infeasibility is the problem itself I decided to solve the problem with [`quadprog`](https://it.mathworks.com/help/optim/ug/quadprog.html). In this specific case, as detailed reporting, the solver can find a feasible solution. 

```
 Iter            Fval  Primal Infeas    Dual Infeas  Complementarity  
    0    9.104051e+01   3.178105e+02   2.204692e+03     1.012527e+01  
    1    7.958060e+01   3.158616e+02   2.191172e+03     1.006490e+01  
    2    8.576712e+01   3.126297e+02   2.168752e+03     9.967296e+00  
    3    1.309022e+02   2.868754e+02   1.990091e+03     9.165382e+00  
    4    2.383756e+03   8.340257e+01   5.785743e+02     3.152992e+01  
    5    4.357418e+03   5.495399e-01   3.812229e+00     4.181151e+01  
    6    4.270918e+03   2.551019e-03   1.769675e-02     1.684785e+00  
    7    4.259477e+03   2.540372e-03   1.762289e-02     1.677836e+00  
    8    4.230085e+03   2.512836e-03   1.743186e-02     1.659863e+00  
    9    4.144354e+03   2.430926e-03   1.686365e-02     1.606384e+00  
   10    3.905361e+03   2.188181e-03   1.517969e-02     1.447743e+00  
   11    3.740884e+03   2.007030e-03   1.392302e-02     1.329019e+00  
   12    2.947298e+03   6.857318e-04   4.757010e-03     4.610475e-01  
   13    2.832549e+03   1.332362e-05   9.242765e-05     9.566793e-03  
   14    2.832482e+03   1.176659e-11   1.126539e-10     1.601277e-08  
   15    2.832482e+03   3.552714e-15   4.202194e-11     8.006387e-12  

Minimum found that satisfies the constraints.

Optimization completed because the objective function is non-decreasing in 
feasible directions, to within the default value of the optimality tolerance,
and constraints are satisfied to within the default value of the constraint tolerance.

Stopping criteria details:

Optimization completed: The relative dual feasibility, 1.295650e-13,
is less than options.OptimalityTolerance = 1.000000e-08, the complementarity measure,
8.006387e-12, is less than options.OptimalityTolerance, and the relative maximum constraint
violation, 1.095398e-17, is less than options.ConstraintTolerance = 1.000000e-08.

Optimization Metric                                            Options
relative dual feasibility =   1.30e-13             OptimalityTolerance =   1e-08 (default)
complementarity measure =   8.01e-12               OptimalityTolerance =   1e-08 (default)
relative max(constraint violation) =   1.10e-17    ConstraintTolerance =   1e-08 (default)
```
Do you have any sudgestion? Do you know if there are some parameters that may be tuned to mitigate the `osqp` behaviour?

In the following, I'm attaching the code where the optimization problem is defined. 
[Infeasibility.zip](https://github.com/oxfordcontrol/osqp/files/2623701/Infeasibility.zip)

Thank you in advance for your support.

**Comment by GiulioRomualdi** [comment]
My fault, there was a bug inside the `quadprog` procedure. We can close the issue.

**Comment by gbanjac** [comment]
Given a QP in the form
```
minimize        0.5 x' P x + q' x
subject to      l <= A x <= u
```
one can show (theoretically) that existence of `dy` satisfying
```
A' dy = 0
l' min(dy,0) + u' max(dy,0) < 0
```
is a certificate that the problem is (primal) infeasible (see [here](http://stanford.edu/~boyd/papers/pdf/admm_infeas.pdf) for more details).

When OSQP reports infeasibility, it also returns such `dy`. In your example, it is stored in `osqp_solution.prim_inf_cert`. You can easily evaluate the conditions above. I obtain the following values
```
norm(constraint'*dy, Inf) = 9.5897e-06
lowerBound'*min(dy,0) + upperBound'*max(dy,0) = -1.6821
```

If I take `x` returned by `quadprog` in your script, it turns out that it does not satisfy constraints, i.e.
```
min(constraint*x - lowerBound) = -219.2470
```
You should probably double check that you are solving equivalent problems with `quadprog` and OSQP.

**Comment by goulart-paul** [comment]
Could you clarify if there is still a problem?   If so I suggest that we close this issue.

**Comment by GiulioRomualdi** [comment]
Thanks to @gbanjac the problem is solved. We can close this issue.

**Comment by GiulioRomualdi** [comment]
For the sake of completeness, I want to explain why in this case `osqp` was not able to find a feasible solution.  

The problem discussed in https://github.com/oxfordcontrol/osqp/issues/109#issue-385174906 has the following form
``` 
minimize        0.5 x' P x + q' x
subject to      A_in x <= u_in
                A_eq x = b_eq
```
While as suggested by @gbanjac https://github.com/oxfordcontrol/osqp/issues/109#issuecomment-442394129 `osqp` solves an optimization problem written in that form. 
``` 
minimize        0.5 x' P x + q' x
subject to      l <= A x <= u
```
In the code attached, I used `-1000` instead of `-inf` (or in C `-OSQP_INFTY`) for the lower bound definition in  the inequality constraints.
As a consequence, this choice caused the infeasibility of the problem i.e. `min(constraint*x - lowerBound) = -219.2470`.

Thus the issue can be easily achieved by using `-inf` instead of `-1000`.
