### ISSUE TITLE
Merge OSQPSettings and OSQPData destruction into osqp_cleanup()?

### ISSUE THREAD

**Issue by hyumo** [oxfordcontrol/osqp#116]
In the C implementation, `OSQPSettings` and `OSQPData` resources have to be destroyed separately from the workspace `osqp_cleanup()`, I am curious if it is possible to merge `OSQPSettings` and `OSQPData` destruction into `OSQPWorkspace` clean up, so that `osqp_cleanup()` cleans up everything?

Thanks for this great library.

**Comment by goulart-paul** [comment]
I think that we would not want to merge them into a single struct, but it might be an idea to create single top-level struct that has pointers to the OSQP Settings / Data / Workspace structs as members.     Creating / destroying a solver would then be a bit shorter I suppose.

This is roughly how OSQP works through its interfaces, i.e. the Matlab and Python interfaces both have a single high-level class 'osqp' that acts as a container for all of the C pieces.

**Comment by hyumo** [comment]
This is what I am doing now:
```c
void new_osqp_cleanup(void *workspace)
{
	OSQPWorkspace* work = (OSQPWorkspace*)workspace;
	if (NULL!=work)
	{
		if (NULL!=work->data)
		{
			c_free(data->A);
			c_free(data->P);
			c_free(data);
		}
		if (NULL!=work->settings)
		{
			c_free(settings);
		}
		osqp_cleanup(work);
	}	
}
```

**Comment by gbanjac** [comment]
I think we are following the idea that the memory is cleaned by the function/program that allocated it. Since OSQP functions do not create the data and settings structures, they should not clean it either. One reason for doing this is because these structures can also be statically allocated.

Also, I think you should not clean matrices `P` and `A` using `c_free` function. This will probably cause a memory leak. You should use [this function](https://github.com/oxfordcontrol/osqp/blob/master/src/cs.c#L44) instead.

**Comment by hyumo** [comment]
Thanks @gbanjac , that's good to know. 

I modified the example from:
https://github.com/oxfordcontrol/osqp/blob/master/examples/osqp_demo.c#L57
I think the example should be fixed as well.

**Comment by gbanjac** [comment]
Actually, in the example above the vectors `P_x`, `P_p`, `P_i`, `A_x`, `A_p`, `A_i` are statically allocated, so the cleanup is done correctly. I assumed you created the matrices with [this function](https://github.com/oxfordcontrol/osqp/blob/master/src/cs.c#L26).

**Comment by hyumo** [comment]
Thanks for pointing out. I am trying to create another language binding for OSQP, I think I will just create a new struct that holds workspace, settings and data. We can probably close this issue. Thanks for the help.

**Comment by gbanjac** [comment]
Based on the comments above, it is clear why we don't want to have a single function that cleans all the OSQP structures. Essentially, one cannot know a priori if the data are allocated statistically or dynamically.

I suggest closing the issue.

**Comment by goulart-paul** [comment]
@hyumo Please do let us know if you create an interface in any additional languages, particularly if it is public.

**Comment by hyumo** [comment]
I will do my best to make it open source. 

I am trying to make a Modelica interface, to be honest, the implementation is quite straight forward thanks to the very clean C interface.
