### ISSUE TITLE
error: cannot convert 'double' to 'linsys_solver_type' in initialization

### ISSUE THREAD

**Issue by Schulze18** [oxfordcontrol/osqp#118]
Hi everyone,

I am having trouble to use the code generated from OSQP. When I try to compile my own code including "osqp.h" and "workspace.h" as described in "example.c", I get the following error: 
`cannot convert 'double' to 'linsys_solver_type' in initialization
`

I faced the same problem using MATLAB and Python interface. I tried to compile using CMake and Codeblocks. 

I resolved the problem doing a "cast" at OSQPSettings settings in "workspace.h":
`
OSQPSettings settings = {(c_float)0.10000000000000001000, (c_float)0.00000100000000000000, 10, 4000, (c_float)0.00100000000000000000, (c_float)0.00100000000000000000, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.60000000000000010000, static_cast<linsys_solver_type>(0.00000000000000000000), 0, 25, 1,
#ifdef PROFILING
(c_float)0.00000000000000000000, 
#endif  // PROFILING
};
`

But I would not like to do this manually every time. Am I missing some Compiler or Linker configuration? The weird thing is that the "example.c" works fine.

**Comment by gbanjac** [comment]
I made a fix in both [Python](https://github.com/oxfordcontrol/osqp-python/commit/7309b550dae04043b264f4aaf1fb223bcf4e3265) and [Matlab](https://github.com/oxfordcontrol/osqp-matlab/commit/eeec2707425b8668d882921e770344aaf628201d). Could you please pull the latest master branch in [osqp-matlab](https://github.com/oxfordcontrol/osqp-matlab) or the latest develop branch in [osqp-python](https://github.com/oxfordcontrol/osqp-python) and try your code now?

**Comment by Schulze18** [comment]
Now it is working, thank you.
