### ISSUE TITLE
internal norm type handling

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/osqp#12]
I suggest that we indicate norm types, in equilibration and elsewhere, via a custom type.  For example, we should define something like

typedef enum {ONE_NORM, TWO_NORM, INF_NORM} norm_t;

and require use of this type when performing equilibration.   The current (1,2,-1) integer flags are not that nice, and possible error prone.

**Comment by bstellato** [comment]
I close it because we removed the norm option in release `0.2.0`.
