### ISSUE TITLE
data scaling issue

### ISSUE THREAD

**Issue by lobpcg** [oxfordcontrol/osqp#120]
**Describe the bug**
Solving Ax=b without constraints is sensitive to scaling of A and b by a small constant, i.e., solving (aA)x=(ab) is not a-invariant. Specifically, for small values the solver fails or, worse, gives wrong answers without any warnings,  e.g., `a = 1e-5` and smaller, although works fine for very large values, up to `a = 1e14`. 

Related to https://github.com/cvxgrp/cvxpy/issues/681 and possibly to https://github.com/cvxgrp/cvxpy/issues/261 and https://groups.google.com/forum/#!searchin/cvxpy/scale|sort:date/cvxpy/BOq4SF_zUh4/FNjuev2nDgAJ

**To Reproduce**
Vary the value of `a` below:

```
from cvxpy import *
import numpy

# Problem data.
m = 20
a = 1e-5
numpy.random.seed(1)
A = a*numpy.random.randn(m, m)
b = a*numpy.random.randn(m)
  
# Construct the problem.
x = Variable(m)
objective = Minimize(sum_squares(A*x - b))
prob = Problem(objective)
prob.solve(solver='OSQP')
sol_linear = numpy.linalg.solve(A, b)
print(sol_linear)

# The optimal objective is returned by prob.solve().
result = prob.solve()
# The optimal value for x is stored in x.value.
print(x.value)
```

**Expected behavior**
The exact solution `x` is mathematically `a`-invariant, as well as the approximate solution by numpy.linalg.solve. The CVXPY/OSQP solution `x` should not be also  `a`-invariant within a reasonable range of `a`? When the solution is wrong, it would be nice to have a warning. 

Why the code works for large a, but not for small a? I guess at some point OSQP computes A.T*A - is that why it stops working for small a?

I see in comments that there is some auto-scaling in OSQP - what does it do in this example?

**Output**
The first vector is the numpy.linalg.solve solution. 
The second vector is the CVXPY/OSQP solution, may be no warnings. 
 
from a = 1e-3 to  a = 1e14

[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]
[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]

a = 1e-5

[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]
[-0.04452038  0.08184306  0.03497562 -0.02511087 -0.0189713   0.01615144
 -0.02238397  0.0031936   0.09219216 -0.05708515  0.00187308  0.01655366
 -0.00348326  0.06954215 -0.04984316 -0.05965816  0.0438942   0.01421084
  0.01033337 -0.00563548]

**Version**
 - OS: Python 3.7.0 64bit for Win 10
 - CVXPY Version: cvxpy-1.0.19 with OSQP built-in

**Additional context**
I have intentionally chosen a rather trivial example. The trouble may get worse for practically interesting cases.  

I am new to CVXPY/OSQP, so apologize in advance if I miss something trivial here...

**Comment by bstellato** [comment]
As @rileyjmurray replied https://github.com/cvxgrp/cvxpy/issues/681#issuecomment-468959088 unfortunately all numerical solvers can only "try" to be scale invariant but numerical operations carry some error by construction. 

Having said that, OSQP internally rescales the problem so that it is easier to solve numerically. `a = 1e-05` values are definitely not in the range of "common problems" and OSQP is not tuned for that. In those cases you can try lowering the tolerance values (`eps_rel, eps_abs`) or increasing the number of scaling iterations (`scaling` parameter). In your case the second option works well, if you execute

```python
prob.solve(solver='OSQP', verbose=True, scaling=20)
```

you should get the solution you expect. In general I suggest to formulate problems so that they contain values between `1e-03` and `1e03` to expect good numerical solvers performance.

**Comment by lobpcg** [comment]
Thanks for your prompt and detailed reply! 

Is there some description of what the implemented scaling actually does? 

I am still curious, why the code works for large a, but not for small a, when the scaling is off?

**Comment by gbanjac** [comment]
@bstellato is right! OSQP does not have any fancy preprocessing routines, but just a simple scaling of the problem data as described in [this paper](http://stanford.edu/~boyd/papers/pdf/osqp.pdf) (Section 5).

I don't necessarily agree that OSQP gives wrong answers without warnings. Interpretation of OSQP status `solved` is that the primal and dual residuals are below some well defined numerical tolerances; see [here](https://osqp.org/docs/solver/index.html#convergence) for more details.

 You can control these tolerances via parameters `eps_rel` and `eps_abs`. For small `a` it is probably the case that the residuals become smaller than `eps_abs` very quickly.

Alternatively, you can help the solver a bit by not passing data that are very ill-conditioned.

**Comment by lobpcg** [comment]
Thanks for the reference! 

In my example, the data are not ill-conditioned, just small. And 1e-5 is not really that small in double-precision. So the issue appears to be due to the absolute stopping criteria, rather than round-off errors. 

It may be worth implementing, as an option, stopping criteria based on some relative residuals, rather than the absolute? E.g., for linear Ax=b solvers, norm(Ax-b) would be the absolute one, cf. http://www.netlib.org/linalg/html_templates/node83.html

**Comment by gbanjac** [comment]
Stopping criteria used by OSQP are combinations of both absolute and relative residuals. You can always set `eps_abs` to a very small number (I think zero is not allowed). The default value for `eps_abs` is `1e-3` so `1e-5` is indeed small relative to this default value.
