### ISSUE TITLE
Exporting Auxiliary Matrices for Code Generation

### ISSUE THREAD

**Issue by Schulze18** [oxfordcontrol/osqp#122]
Hi guys,

I was wondering if there is a way to export auxiliary matrices in generated code to update the data vector in the QP problem. For example, it is common in MPC problems that your "q" matrix in "0.5 x' P x + q' x" is actually "F'x(t)" ( x(t) in this case is the state of the system). This also happens with the lower and upper constraints vectors, which are usually defined by "upper = U_max + E*x(t)". The matrices F, U_max, and E usually changes with the controller horizons, so, it is really boring to recalculate them in C/C++ after you have already done it in Matlab or Python.

If there is not already a way to that, how could I do that? Reading the sources files, it looks to me that is necessary to modify the OSQPData struct definition in "types.h" to add new matrices and vectors, and also include "write_vec" for this vectors/matrices in "render_workspace.m" (Matlab Interface) and "utils.py" (Python Interface).

**Comment by gbanjac** [comment]
I don't see what is a problem in computing `q_new = F'x(t)` outside of OSQP functions and then updating  `q` with `q_new`.

And how is this related to Matlab and Python? If you are using OSQP from Matlab or Python, why are you generating the C code?

**Comment by gbanjac** [comment]
And no, it is not possible to export auxiliary matrices in generated code.

**Comment by bstellato** [comment]
Unfortunately what you ask would require a QP canonicalizer which is not in the scope of OSQP as a solver. I know there is some future plan to make [cvxpy](https://github.com/cvxgrp/cvxpy) support code generation features which would solve your problem, but not much is available now.

For now, I suggest you to look at the [OSQP eigen](https://github.com/robotology/osqp-eigen) interface which has been designed by people mostly working on MPC. You can find a C++ example where the problem data gets updated [here](https://github.com/robotology/osqp-eigen/blob/master/example/src/MPCExample.cpp). I believe the code could be directly adapted for a code-generated OSQP since the update and solve functions stay the same.

**Comment by Schulze18** [comment]
Thank you for the answer @gbanjac 

My application runs in C++, it is a plugin for ROS. But I design my predictive controllers in Matlab, because I have many more tools at Matlab for that. The problem is not computing `F'x(t)`, but computing `F`, what changes for every set of horizons and specifications from MPC.

**Comment by Schulze18** [comment]
Thank you @bstellato , I will look at eigen interface.

**Comment by gbanjac** [comment]
Btw, are you using the condensed or sparse formulation of the MPC problem? In other words, do you eliminate the state variables from the problem?

**Comment by Schulze18** [comment]
I believe I am using a sparse formulation. I am using control and control rate constraints right now, what demands me to inform the past control actions. But I want my code to be the most general as possible, in the case I want to include state and output constraints. I don't know if I understood what you said @gbanjac , but I need to update the matrices at each control cycle because some of them depends on the state variables.

**Comment by gbanjac** [comment]
I asked if the optimization variable (vector) in your MPC problem had the form `(u(0),u(1),...,u(N-1))` or `(x(0),u(0),x(1),u(1),...,x(N))`.

If you are using the former (condensed) representation, then you have a smaller number of optimization variables, but your data matrices are usually dense. If this is the case, then computing matrix `F` involves some matrix-matrix multiplications and can be annoying to compute in each control cycle.

Alternatively, you can use the latter (sparse) representation which involves a larger number of variables, but the data matrices are sparse. Not only you will avoid performing matrix-matrix multiplications when constructing your problem data, but OSQP is also very efficient when working with sparse matrices. We use this sparse formulation in [this example](https://osqp.org/docs/examples/mpc.html).

**Comment by Schulze18** [comment]
I understood now, I am using the condensed representation.

**Comment by gbanjac** [comment]
I suggest closing this issue. Feel free to use [our forum](https://groups.google.com/forum/#!forum/osqp) for discussions on how to use OSQP for solving nonlinear MPC problems.
