### ISSUE TITLE
Is possible to solve portfolio optimization?

### ISSUE THREAD

**Issue by aykurtis** [oxfordcontrol/osqp#123]
I am trying to solve portfolio optimization with asset allocation constraints.
Is possible to solve such quadratic constraint problems with OSQP?

Thanks,

**Comment by gbanjac** [comment]
Yes. Please have a look [here](https://osqp.org/docs/examples/portfolio.html) for more details.

**Comment by gbanjac** [comment]
Btw, what do you mean by "quadratic constraint problems"? Note that OSQP can solve only problems with polyhedral (not quadratic) constraints.

**Comment by aykurtis** [comment]
I meant by "quadratic constraint problems" 

I may define constraints for a portfolio optimization problem,
For example, 
-First costraint: Sum of assets allocations  must be equal to 100%
-Second constraint:   Some specific assets allocations in portfolio must be less than  %10. 
Also, I may define different allocation constraints for each asset.

My goal function is minimizing **portfolio variance - lamda * Portfolio Return** 
(lamda is a constant)

Solver must find asset allocations under above constraints.

Is this possible with OSQP? 
I develop in c# and  am not able to run C++ code.
A simple c# wrapper may be good to use OSQP in .net platform.

 Thanks,

**Comment by aykurtis** [comment]
I meant by "quadratic constraint problems" 

I may define constraints for a portfolio optimization problem,
For example, 
-First costraint: Sum of assets allocations  must be equal to 100%
-Second constraint:   Some specific assets allocations in portfolio must be less than  %10. 
Also, I may define different allocation constraints for each asset.

My goal function is minimizing **portfolio variance - lamda * Portfolio Return** 
(lamda is a constant)

Solver must find asset allocations under above constraints.

Is this possible with OSQP? 
I develop in c# and  am not able to run C++ code.
A simple c# wrapper may be good to use OSQP in .net platform.

 Thanks,

**Comment by bstellato** [comment]
Looks like your problem has quadratic cost and linear constraints. So yes, osqp can solve it. At the moment we do not support quadratic constraints.

**Comment by gbanjac** [comment]
Also, we don’t have any current plans to develop a C# wrapper for OSQP. We have interfaces for C/C++, Fortran, Matlab, Python, R, Julia, Rust, so you might want to try one of these.

**Comment by aykurtis** [comment]
Yes, my constraints are linear.  

Thanks,
