### ISSUE TITLE
Crash when there are no constraints.

### ISSUE THREAD

**Issue by kermado** [oxfordcontrol/osqp#129]
When I have no constraints and I want to setup the csc matrix A, should I need to initialize A->p fully? For example, given that n = 2 and m = 0:

This works:
```
c_int A_p[3] = {0, 0, 0};
```

This crashes:
```
c_int A_p[1];
A_p[0] = 0;
```

This also crashes:
```
c_int A_p[3];
A_p[0] = 0;
```

I thought that for n=2, m=0 then the dimensions of A are 0x2. In this case, and from my reading of the [documentation](https://people.sc.fsu.edu/~jburkardt/data/cc/cc.html) linked for csc matrices, it seems that we should need only set the first element of A_p. I don't know what it means to set the values after the first element. It's seems odd that OSQP should be reading them.

**Comment by bstellato** [comment]
`A_p` always needs to be of dimension `n+1`. This is independent from the number of nonzeros. The other vectors defining `A` change dimension depending on the number of nonzeros but `A_p` does not. The first line you described is the right one.

Our definition matches what people use for python sparse matrices

```python
>>> import scipy.sparse as spa
>>> A = spa.csc_matrix((0, 2))
>>> A.indptr
array([0, 0, 0], dtype=int32)
```

**Comment by kermado** [comment]
Thanks.
