### ISSUE TITLE
Rho update tic overwrites runtime tic

### ISSUE THREAD

**Issue by Benny44** [oxfordcontrol/osqp#130]
Hey guys,

I think there is an issue with the timings. I noticed this because as I was playing around, I sometimes got the same number of iterations (1500ish) but saw a runtime that was ten times as low. I am pretty sure the problem is in osqp.c, in the call to osqp_tic on line 1258 (for updating rho) overwriting the call on 321 (keeping track of runtime). Can you check this and fix it if necessary? Thanks.

Best,
Ben

**Comment by Benny44** [comment]
I think this also explains issue #115 Timings don't seem to be monotonic.

**Comment by gbanjac** [comment]
Indeed, this issue is related to https://github.com/oxfordcontrol/osqp/issues/115 that should be fixed in [this commit](https://github.com/oxfordcontrol/osqp/commit/a46b5f6e42519105102540e0a7e9985e5928d12c) in `develop` branch. From which language are you using OSQP?

**Comment by Benny44** [comment]
Hey, I was using Matlab, which pull from the master branch. I just checked out the develop branch of osqp_sources, and I can confirm this fix works. Thanks.
