### ISSUE TITLE
Build fails when PRINTING is not defined

### ISSUE THREAD

**Issue by rdeits** [oxfordcontrol/osqp#131]
Undefining `PRINTING` in `osqp_configure.h` results in the following build error: 

```
../../rt/3rdparty/osqp/src/util.c: In function ‘copy_settings’:
../../rt/3rdparty/osqp/src/util.c:227:3: error: implicit declaration of function ‘memcpy’ [-Werror=implicit-function-declaration]
   memcpy(new, settings, sizeof(OSQPSettings));
   ^
../../rt/3rdparty/osqp/src/util.c:227:3: error: incompatible implicit declaration of built-in function ‘memcpy’ [-Werror]
../../rt/3rdparty/osqp/src/util.c:227:3: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
cc1: all warnings being treated as errors
```

This happens because `<string.h>` is only included when `PRINTING` is defined. 

This isn't actually a problem for me (I just ran into it while testing out build flags), but I figured it was worth mentioning.

**Comment by goulart-paul** [comment]
I think we could fix this by just including `<string.h>` along with `<stdlib.h>` [here](https://github.com/oxfordcontrol/osqp/blob/1287329ddf48d8a8982a7d0774323a492895beda/include/glob_opts.h#L77) when `EMBEDDED` is not defined, and I don't see any harm in doing so.   @bstellato do you agree?

**Comment by bstellato** [comment]
I would rather copy the settings explicitly. We do not need `string.h` just to copy a structure. I made  a PR to fix this and added unittests with `PRINTING=OFF`.
