### ISSUE TITLE
Support using custom allocators with OSQP

### ISSUE THREAD

**Issue by nikalra** [oxfordcontrol/osqp#136]
OSQP potentially performs quite a few allocations and in a multi-threaded context, that results in a kernel-level lock for setting up the problem.

In those cases, we'd potentially like to use a custom allocator with OSQP that avoids these problems, enabling us to do the work of setting up problems asynchronously while waiting for other results.

**Comment by nikalra** [comment]
@bstellato @gbanjac Would this be a workflow that OSQP would like to support? 

Being able to use custom allocators is extremely important for our project -- just trying to get some clarity if we should go the fork route for this functionality or if this change could be integrated into this repo?

**Comment by gbanjac** [comment]
@nikalra Many thanks for the PR and sorry for the delayed response!

Yes, we would definitely like to integrate your PR. However, before just merging it to the `master` branch, we would like to make sure that other interfaces (that use this repo as a submodule) still work with this change. We were busy with other things, but will definitely have a look at this in the following days.

**Comment by bstellato** [comment]
I have just made a PR proposing a solution via cmake #140
