### ISSUE TITLE
`osqp_setup` doesn't always check the return value of `malloc` and friends

### ISSUE THREAD

**Issue by ebarnard** [oxfordcontrol/osqp#149]
I noticed this while updating the Rust interface for #124. `osqp_setup` only checks whether the allocation of `work` succeeds. It does not check the results of any of the other allocations it performs. e.g.
https://github.com/oxfordcontrol/osqp/blob/13c02dc82c5064c137a8fc85055deda64ea585d5/src/osqp.c#L114

**Comment by gbanjac** [comment]
Fixed via https://github.com/oxfordcontrol/osqp/pull/150
