### ISSUE TITLE
C/C++ interface csc struct - documentation ambiguity on compressed-column vs. triplet format

### ISSUE THREAD

**Issue by elokdae** [oxfordcontrol/osqp#155]
Hello,

I found the documentation ambiguous regarding matrix format that is passed to osqp_setup in the OSQPData struct. csc struct description reads 'Matrix in compressed-column or triplet form' which led me to believe that osqp_setup accepts matrices in triplet format also. This is what I chose because I found it much easier to populate than compressed-column.

May I suggest that you clarify the documentation to make it less ambiguous, or even better accept triplet format matrices in osqp_setup? Again I found triplet format much more user friendly to work with than compressed-column. I ended up using 'triplet_to_csc' function, which seems to be meant for internal use only.

Thanks otherwise for a great solver :)

Ezzat Elokda

**Comment by gbanjac** [comment]
This should now be fixed.
