### ISSUE TITLE
QP formulation of Huber fitting in OSQP documentation

### ISSUE THREAD

**Issue by cling18** [oxfordcontrol/osqp#156]
Hi, thank you for the great work! Recently, I was using OSQP to solve Huber fitting problems and it seems that the quadratic formulation of Huber fitting in https://osqp.org/docs/examples/huber.html is not correct (Please refer to https://web.stanford.edu/~boyd/papers/pdf/osqp.pdf for the correct formulation).

The formulation in osqp_benchmark is correct
https://github.com/oxfordcontrol/osqp_benchmarks/blob/f10fd040f24c3c68bda58378d7dcfda928c2f85d/problem_classes/huber.py#L40
It would be helpful to correct the QP formulation of Huber fitting in the documentation, unless I miss something.

**Comment by gbanjac** [comment]
There are various QP formulations of the Huber fitting problem. The formulation described in the OSQP paper is taken from Boyd's book on Convex Optimization, while the other one is taken from [this paper](https://ieeexplore.ieee.org/document/877518) (eq. (9)).

There is yet another QP formulation (eq. (24) in the paper above). You can test different formulations on your problems and see which one works best for you.

**Comment by cling18** [comment]
Thanks for the reply! I went through the paper and I'm convinced that it is indeed one of the QP formulation for Huber fitting.
