### ISSUE TITLE
Error building the source files on macOS (10.12.5)

### ISSUE THREAD

**Issue by chensiquan** [oxfordcontrol/osqp#16]
An error occurs when building the source files on macOS (10.12.5).

> [ 68%] Generating unittests data files using Python
Traceback (most recent call last):
  File "generate_tests_data.py", line 3, in <module>
    import basic_qp.generate_problem
  File "/Users/user/Desktop/OSQP_TEST/osqp/tests/basic_qp/generate_problem.py", line 3, in <module>
    import utils.codegen_utils as cu
  File "/Users/user/Desktop/OSQP_TEST/osqp/tests/utils/codegen_utils.py", line 3, in <module>
    from builtins import dict
ImportError: No module named builtins
make[2]: *** [../tests/basic_qp/data.h] Error 1
make[1]: *** [CMakeFiles/osqp_tester_direct.dir/all] Error 2
make: *** [all] Error 2

The macOS (10.12.5) has a built-in Python 2.7 library, and CMAKE will use the built-in Python library if not specified. The module `builtins` is a Python3 module, and it has a different name `__builtin__` in Python2. 

My solution is to add a Python version requirement in `CMakeLists.txt`, and then CMAKE will find the correct Python3 library I installed. 

It should be also noticed that the function `random` in `scipy.sparse` (used in `/osqp/tests/utils/codegen_utils.py`) was added in scipy after v0.17.0, and there should also be a version requirement for scipy.

**Comment by bstellato** [comment]
It should be fixed now 92613ef43994e47dcaab0d43aed7e0360e3f5328.

Let me know if it solves the problem.

**Comment by chensiquan** [comment]
CMAKE is still looking for the built-in Python 2.7. 

> -- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Found NUMPY: 1.8.0rc1 (found version "1.8.0rc1") 
-- Found SCIPY: 0.13.0b1 (found version "0.13.0b1") 
CMake Error at CMakeLists.txt:304 (message):
  You need scipy python module installed to generate unittests.  If you do
  not want to compile the unittests pass -DUNITTESTS=OFF to cmake.

I changed line 290 `find_package(PythonInterp)` to `find_package(PythonInterp 3)` in CMakeList.txt and the problem is fixed. 

> -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 (found suitable version "3.6.1", minimum required is "3") 
-- Found NUMPY: 1.12.1 (found version "1.12.1") 
-- Found SCIPY: 0.19.0 (found version "0.19.0") 
-- Found Python __FUTURE__
-- Configuring done
-- Generating done

**Comment by bstellato** [comment]
The change you proposed would break cmake on any computer still using Python 2. The behavior of cmake is correct: it looks for the default python interpreter you get when you run `python` from the terminal.

I suspect you installed Python 3 on MacOS from a third party (probably homebrew) and now you have the executable called `python3`. I suggest you to use `virtualenv` to load your python version correctly. Have a look at [this](http://www.marinamele.com/2014/07/install-python3-on-mac-os-x-and-use-virtualenv-and-virtualenvwrapper.html). In this way you do not have to execute `python3` but just `python`.

A possible alternative is to use Anaconda installation and setup an environment with your favorite python version.

**Comment by chensiquan** [comment]
Sorry that I didn't notice that Python2 support was added. 

Codes work well after I updated scipy.

Thank you.
