### ISSUE TITLE
CMake error on qdldl_sources

### ISSUE THREAD

**Issue by baerbock** [oxfordcontrol/osqp#161]
I'm getting the following error:
```
CMake Error at lin_sys/direct/qdldl/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    ./osqp/src/osqp/lin_sys/direct/qdldl/qdldl_sources

  does not contain a CMakeLists.txt file.
```

Here is my CMakeOutput.log: https://pastebin.com/F4cucd6e

I'm building from source at ArchLinux:
```
	cmake -DCMAKE_INSTALL_PREFIX:PATH=${pkgdir} -G "Unix Makefiles" ..
	cmake --build .
```

**Comment by gbanjac** [comment]
It seems that your `qdldl_sources` directory is empty. Have you cloned the repository with `git clone --recursive https://github.com/oxfordcontrol/osqp`? Note that QDLDL is a submodule in the OSQP repository.

**Comment by gbanjac** [comment]
Have a look [here](https://osqp.org/docs/get_started/sources.html) on how to build OSQP from sources.

**Comment by baerbock** [comment]
@gbanjac I've actually missed to clone the submodules. Thank you very much!

**Comment by signproduction** [comment]
The --recursive option work in the command line.
However the instructions offer another way to get source code which is from bintray.com.

_You first need to get the sources from one of these two options:

Download the compressed file from bintray.com.
Clone the repository_
The same error occurs if we try to cMake using the source code in the zip files from bintray.com.

What to do then?

**Comment by bstellato** [comment]
It should not occur. Please run it from the file from the bintray sources of the [latest osqp release 0.6.0](https://bintray.com/bstellato/generic/download_file?file_path=OSQP%2F0.6.0%2Fosqp-0.6.0.tar.gz). It should have the qdldl sources inside.

**Comment by signproduction** [comment]
Thank you, bstellato.  This link worked.

Do you by any chance have analogous links for versions 5 and 4.1?  I tried getting these versions from bintray.com and ran into the same error.

On a related note, if I have version 6, do you see any reason why I would try any prior versions?
