### ISSUE TITLE
The theory for the code

### ISSUE THREAD

**Issue by Wonsa0823** [oxfordcontrol/osqp#172]
Could you tell me the code is based on the paper(https://stanford.edu/~boyd/papers/pdf/admm_infeas.pdf) that you mention in the README?

**Comment by goulart-paul** [comment]
The OSQP code is largely based on the paper here: https://arxiv.org/abs/1711.08013

The infeasibility checks in the code are based on the paper you linked to.

IF you have questions about how the algorithm works, please post them to the OSQP discussion forum here: https://osqp.discourse.group
