### ISSUE TITLE
Error in osqpSolve(private$.work) : external pointer is not valid

### ISSUE THREAD

**Issue by naghmeh6** [oxfordcontrol/osqp#173]
I am trying to solve a quadratic program by R-OSQP, I got this error

         Error in osqpSolve(private$.work) : external pointer is not valid

what is that for? the size of P is 1803*1803 and A is 2 times bigger

**Comment by bstellato** [comment]
Can you please write a full example reporting the error? Also, please do not open multiple issues for the same thing. I am closing this one in favor of https://github.com/oxfordcontrol/osqp-r/issues/8

For this kind of questions please use the [forum](https://osqp.discourse.group/).
