### ISSUE TITLE
Solver doesn't converge

### ISSUE THREAD

**Issue by EdsterG** [oxfordcontrol/osqp#18]
I'm not too familiar with the settings and how they affect the optimization problem, however when I modify osqp_demo_direct.c with the following values, the solver doesn't converge:

```
    // Load problem data
    c_float P_x[1] = {2.00004};
    c_int P_nnz = 1;
    c_int P_i[1] = {0};
    c_int P_p[5] = {0, 1, 1, 1, 1};
    c_float q[4] = {-2.00035, 0, 1, 1};
    c_float A_x[8] = {-200, 1, 10, 1, 1, 1, -1, 1};
    c_int A_nnz = 8;
    c_int A_i[8] = {0, 1, 0, 2, 0, 3, 0, 4};
    c_int A_p[5] = {0, 2, 4, 6, 8};
    c_float l[5] = {-1000, 9.9, 0.9, 0, 0};
    c_float u[5] = {-1000, 10.1, 1.1, 1e+30, 1e+30};
    c_int n = 4;
    c_int m = 1;
```

**Comment by gbanjac** [comment]
With the data above, it seems like you should set `m=5` instead of `m=1`.
It is probably easier to try these examples in Python:
```python
import numpy as np
import scipy.sparse as spa
import osqp

# Define problem data
P = spa.diags([2.00004, 0, 0, 0]).tocsc()
A = spa.csc_matrix([[-200, 10, 1, -1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
q = np.array([-2.00035, 0, 1, 1])
l = np.array([-1000, 9.9, 0.9, 0, 0])
u = np.array([-1000, 10.1, 1.1, np.inf, np.inf])
prob = osqp.OSQP()
prob.setup(P, q ,A ,l, u)
res = prob.solve()
```
First-order methods are sometimes sensitive to the choice of algorithm parameter. We will solve this issue in the next release.

If you get that the primal residual is much bigger than the dual residual, this probably means that you should decrease the value of rho. If you instead set `rho=1e-3`, the method will converge.
```python
prob.setup(P, q, A, l, u, rho=1e-3)
```

**Comment by EdsterG** [comment]
Great, that value of rho fixes it. However, now a previously working model breaks with the new value of rho. Even when I set auto_rho=True, it doesn't always solve all of the models.

When do you expect the next release to happen? I'm currently using OSQP as part of a motion planning algorithm. I'll probably start exploring other options until the next release of OSQP.

**Comment by bstellato** [comment]
The `auto_rho` feature in the current `master` branch is not reliable. I suggest not to use it, but to adjust `rho` manually at the moment. The number of iterations can greatly be reduced in that way. We plan on releasing the new version in the next few weeks. 

Do you solve the motion planning problem multiple times with slightly changing data? If it is a parametric program - especially if only the vectors change - OSQP can greatly simplify the computations by using warm starting and caching the factorization of the previous solve. Happy to discuss the issues related to your particular problem formulation in the [forum](https://groups.google.com/forum/#!forum/osqp).

**Comment by EdsterG** [comment]
Will eagerly wait for the next release.

Currently, the sparsity structure of the A matrix and P matrix changes between runs. However, the dimensions don't change. Not sure if this is considered "slightly" changing the data.

**Comment by bstellato** [comment]
I will keep you informed about the next release!

If the sparsity pattern changes, a new setup has to be performed again. However, if the subsequent solutions are close, warm starting can significantly reduce the number of iterations required. See [here](http://osqp.readthedocs.io/en/develop/interfaces/CC++.html#warm-start) for how to use it with the C/C++ interface.

**Comment by bstellato** [comment]
The [new release](https://github.com/oxfordcontrol/osqp/releases/tag/v0.2.0) is online! Can you please try your previously working model that had problems with the a different `rho` value? OSQP should now figure auto the best `rho` automatically and return it.

**Comment by bstellato** [comment]
I close it since convergence has improved a lot with this version. Please let me know if you have other issues.
