### ISSUE TITLE
Update docs for upper triangular P

### ISSUE THREAD

**Issue by bstellato** [oxfordcontrol/osqp#183]
New C interface allows for simplicity only upper triangular `P`. The other interface convert `P` to upper triangular in case it is not. We should make sure the new docs and demos clarify this change. @gbanjac could you please fix that?

**Comment by gbanjac** [comment]
Some of this has already been updated in the docs. You should merge `release-0.6.0` branch to `master` to see this on `osqp.org/docs`. I will update the demos accordingly.

**Comment by bstellato** [comment]
Ok! I am waiting for the python packaging to finish and I will do so.

**Comment by gbanjac** [comment]
I see now that the demos are already updated.
