### ISSUE TITLE
No version available for pip on linux

### ISSUE THREAD

**Issue by SteveDiamond** [oxfordcontrol/osqp#20]
I can't install OSQP via pip on linux. This actually makes it impossible to install the new cvxpy 1.0 on linux. I'd really appreciate it if you could upload something to pypi as soon as possible.

**Comment by bstellato** [comment]
We are currently working on it by distributing also the sources for linux. It is not obvious since there is `cmake` involved. We will create the next patch version and fix it as soon as possible.

**Comment by bstellato** [comment]
It should be fixed now in version `0.1.3` d06cc8cfbfab9f36aec49052202b56338f9257d3. Let me know if it works.

**Comment by SteveDiamond** [comment]
Seems to work! Thanks for fixing this so quickly!
