### ISSUE TITLE
Updating Problem Matrices via Mex Interface

### ISSUE THREAD

**Issue by Ajin2305** [oxfordcontrol/osqp#203]
I have successfully managed to run OSQP on Matlab for my problem. After performing code generation on the previously working problem setup, i obtained a MEX file. This  file gives me access to functionalities that help me solving problems, updating the limits, cost and problem matrices. I am able to update everything but the problem matrices (P and A). Matlab doesn't log an error but crashes. I am following the syntax given on the website. Kindly advice

**Comment by Ajin2305** [comment]
Here is a sample script which crashes Matlab. I have provided the necessary data in a zip file.
`%Test Mex function

load('oldDAT.mat')

% Setting up osqp
prob = osqp;
prob.setup(2*sparse(Px), q, sparse(Ax), low, upp, 'verbose', 0,'eps_rel',1e-8,'eps_abs',1e-8); %Problem setup

%Code Generation
prob.codegen('code', 'parameters', 'matrices', 'mexname', 'emosqp'); % Generates a MEX-FILE emosqp 

load('newDAT.mat')
%Updating the MEX file
emosqp('update_lin_cost', q)
emosqp('update_bounds', low, upp);
%Crashes after this
emosqp('update_A', nonzeros(Ax), [], 0);
emosqp('update_P', nonzeros(triu(Px)),[],0);`

[OSQP.zip](https://github.com/oxfordcontrol/osqp/files/3609236/OSQP.zip)

**Comment by goulart-paul** [comment]
I have tested @imciner2's fix and confirm that it works for me.

**Comment by Ajin2305** [comment]
It works for me as well thanks!
