### ISSUE TITLE
version incompatibility

### ISSUE THREAD

**Issue by vivianemarty** [oxfordcontrol/osqp#209]
I wanted to run the code (which was using osqp 0.5.0) with my osqp 0.6.1 and I got version errors. The problem was fixed when I installed the osqp 0.5.0.
I just want to let you know that the version are somehow not compatible.

**Comment by goulart-paul** [comment]
There was a change in the `osqp_setup` function between 0.5 and 0.6.   It is described in the release notes here: https://github.com/oxfordcontrol/osqp/releases/tag/v0.6.0
