### ISSUE TITLE
How to minimize an quadratic objective function with constraint violation using penalty method

### ISSUE THREAD

**Issue by k-maheshkumar** [oxfordcontrol/osqp#21]
I want to minimize an indefinite quadratic function with both equality and inequality constraints that may get violated depending on various factors. So I want to use l1 penalty method that penalizes the violating constraints.

![selection_037](https://user-images.githubusercontent.com/15979124/32221899-92312948-be37-11e7-995b-785272cda826.png)

for example,
I have modified an [example](http://osqp.readthedocs.io/en/latest/examples/Python/demo.html), to violate the constraints.

```
import osqp
import scipy.sparse as sparse
import numpy as np

# Define problem data
P = sparse.csc_matrix([[4., 1.], [1., 2.]])
q = np.array([1., 1.])
A = sparse.csc_matrix([[1., 0.], [0., 1.], [1., 0.], [0., 1.]])
l = np.array([0., 0., 0.2, 1.1])
u = np.array([1., 1., 0.2, 1.1])

# Create an OSQP object
prob = osqp.OSQP()

# Setup workspace and change alpha parameter
prob.setup(P, q, A, l, u, alpha=1.0)

# Solve problem
res = prob.solve()
print res.x

```

Obviously, this is an infeasible problem, so we need to change the objective function to penalize the error. So, I need help to formulate this problem that can be solved using osqp's python interface.

**Comment by bstellato** [comment]
[CVXPY 1.0](https://cvxgrp.github.io/cvxpy/index.html) now supports QP parsing and is interfaced directly to OSQP. It can make your life much easier.

To define and solve your problem in CVXPY you can run the following script

```python
import cvxpy
import scipy.sparse as sparse
import numpy as np

# Define problem data
P = sparse.csc_matrix([[4., 1.], [1., 2.]])
q = np.array([1., 1.])
A = sparse.csc_matrix([[1., 0.], [0., 1.], [1., 0.], [0., 1.]])
l = np.array([0., 0., 0.2, 1.1])
u = np.array([1., 1., 0.2, 1.1])
mu = 1  # Penalty parameter


# Define CVXPY problem
x = cvxpy.Variable(2)
# Standard objective
objective = cvxpy.quad_form(x, P) + q * x 
# Penalty part of the objective
objective += mu * (cvxpy.norm1(A * x - u) + cvxpy.norm1(-A * x + l))
problem = cvxpy.Problem(cvxpy.Minimize(objective), [])
results = problem.solve(solver=cvxpy.OSQP, verbose=True)
```

For QP modeling questions, I suggest to use the [OSQP forum](https://groups.google.com/forum/#!forum/osqp).

**Comment by k-maheshkumar** [comment]
Above method didn't work for my application as it is a non-convex problem,

`import cvxpy
import scipy.sparse as sparse
import numpy as np
import dccp

# Define problem data
P = sparse.csc_matrix([[2., -4., 0.],
                       [0., 4., -4.],
                       [0., 0., 2.]])
q = np.array([1., 1., 0.])
A = sparse.csc_matrix([[-1., 1., 0.],
                       [0., -1., 1.],
                       [1., 0., 0.],
                       [0., 0., 1.],
                       [1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])
l = np.array([-0.3, -0.3, 0.2, 0.7, -0.3, -0.3, -0.3])
u = np.array([0.3, 0.3, 0.2, 0.7, 1.1, 1.1, 1.1])
mu = 1  # Penalty parameter

mu = 15  # Penalty parameter

# P =  .5 * (P + P.transpose())
# Define CVXPY problem
x = cvxpy.Variable(P.shape[1])

# Standard objective
objective = cvxpy.quad_form(x, P) + q * x

# Penalty part of the objective
objective += mu * (cvxpy.norm1(A * x - u) + cvxpy.norm1(-A * x + l))


problem = cvxpy.Problem(cvxpy.Minimize(objective), [])
results = problem.solve(solver=cvxpy.OSQP, verbose=False)
print results
print x.value
`

I get the following error,

`/usr/bin/python2.7 /sqpproblem/probSlack2.py
Traceback (most recent call last):
  File "/sqpproblem/probSlack2.py", line 54, in <module>
    results = problem.solve(solver=cvxpy.OSQP, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/problems/problem.py", line 247, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/problems/problem.py", line 359, in _solve
    raise e
cvxpy.error.DCPError: Problem does not follow DCP rules.

Process finished with exit code 1
`

**Comment by bstellato** [comment]
The problem is non convex because your matrix `P`
```python
P = sparse.csc_matrix([[2., -4., 0.],
                       [0., 4., -4.],
                       [0., 0., 2.]])
```

is not symmetric positive semidefinite. Are you sure your problem is nonconvex? Maybe it is just a modeling issue? I suggest you to have a look at the [convex optimization book](https://web.stanford.edu/~boyd/cvxbook/).

I close since it is not a solver issue.  The rest of the discussion is [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osqp/M0riD2CMYgQ/AuSbcAZQBgAJ).
