### ISSUE TITLE
Issues in Linking Library for Running OSQP on C

### ISSUE THREAD

**Issue by Ajin2305** [oxfordcontrol/osqp#213]
Hi, 

I have performed installation of OSQP as per the guide on the website. After which i wanted to run the example script on my IDE. So, included the folder with header files and linked the static libraries (.a) as per the website. I also included linker options.  But i get an error "cannot find -losqp ".

Kindly advice
<img width="945" alt="Error_codeBlocks" src="https://user-images.githubusercontent.com/31613200/66929698-c6c04b00-f033-11e9-9b21-c648f6ffe5eb.PNG">
<img width="179" alt="files" src="https://user-images.githubusercontent.com/31613200/66929699-c6c04b00-f033-11e9-88e2-cd9011ab49d1.PNG">
<img width="537" alt="Linker settings" src="https://user-images.githubusercontent.com/31613200/66929700-c758e180-f033-11e9-9908-233b234eb9a6.PNG">
<img width="533" alt="searchdir" src="https://user-images.githubusercontent.com/31613200/66929702-c758e180-f033-11e9-8f8d-9b9968130be8.PNG">

**Comment by goulart-paul** [comment]
Your problem does not appear to be directly related to OSQP, but is rather one of not having the build options of your IDE configured correctly for whichever application you are trying to use OSQP with.   There are two likely possibilities:

1) You have not include the correct path for the osqp static library when configuring the link libraries.   You have the linker option `-Losqp\lib`, but that path may not exist.   It would perhaps be better to use an absolute path.

2) You have included the correct path for the library but the static library is not actually there.   Please verify that `libosqp.a` actually exists somewhere and is in the right place.  Is it in `C:\Program Files (x86)\osqp\lib`?

**Comment by Ajin2305** [comment]
I have resolved this issue. It had something to do with the Toolchain executable in my IDE. The default version did not allow the linking to happen.
