### ISSUE TITLE
Segmentation fault  in osqp_setup

### ISSUE THREAD

**Issue by jhx2002** [oxfordcontrol/osqp#214]
When calling osqp_setup segment fault , but there is no any error messages.
Segmentation fault (core dumped)

**Comment by goulart-paul** [comment]
You have not provided enough information for us to making any useful suggestion.   Please provide a minimal example showing the inputs to `osqp_setup` that you used that led to a seg fault.

**Comment by jhx2002** [comment]
using gdb corefile, got :
`
Reading symbols from ./test_example...(no debugging symbols found)...done.
[New LWP 1369]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./test_example ../data/testmap.png'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:332
332	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.

`
