### ISSUE TITLE
how to reuse OSQPWorkspace *work ? 

### ISSUE THREAD

**Issue by jhx2002** [oxfordcontrol/osqp#220]
It seems difficult to reuse OSQPWorkspace,  because there is mem alloc in each call of 
```
int ret = osqp_setup(&work, &data, &settings_);
```
If I call osqp_clean after each ```osqp_solve```,  will it create memory fragment ?

**Comment by imciner2** [comment]
How are you planning on reusing the OSQPWorkspace structure?

The `osqp_cleanup` function will go through and free all memory that OSQP allocated in the workspace, but that is usually only needed after you are finished with your problems.

**Comment by imciner2** [comment]
Also, questions like these are more suited to the OSQP discourse forum here: https://osqp.discourse.group/ rather than as GitHub issues.
