### ISSUE TITLE
Unable to find function definition when CUDA_SUPPORT=ON

### ISSUE THREAD

**Issue by jiesky** [oxfordcontrol/osqp#222]
Execuse me. My code works well when CUDA_SUPPORT=OFF on osqp-cuda-1.0, but when i set CUDA_SUPPORT=ON, reinstall..., and then i run same code ,it core. 

message on terminal is as follow:
  //usr/local/lib/libosqp.so: undefined reference to `cusparseCreateMatDescr'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseCreate'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseCsrmvEx'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseXcoo2csr'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseDestroyMatDescr'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseDgthr'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseXcsr2coo'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseXcoosortByRow'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseDestroy'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseSetMatIndexBase'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseCreateIdentityPermutation'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseSetMatType'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseXcoosort_bufferSizeExt'

  //usr/local/lib/libosqp.so: undefined reference to `cusparseCsrmvEx_bufferSize'

  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you tell  me what happens? Thanks

**Comment by jiesky** [comment]
nvidia binary driver-version 410.78 from nvidia-410 is installed

**Comment by gbanjac** [comment]
Looks like you are not linking against the `cusparse` library. Can you run the `osqp_demo` executable?

**Comment by jiesky** [comment]
> Looks like you are not linking against the `cusparse` library. Can you run the `osqp_demo` executable?

Hi, I run `osqp_demo`, it also core,  and message on terminal is same as that above. what can i do to solve this problem? thanks

**Comment by micschub** [comment]
What GPU model are you using? And which Toolkit version have you installed? You can get the version by running “nvcc --version“ .

**Comment by jiesky** [comment]
> What GPU model are you using? And which Toolkit version have you installed? You can get the version by running “nvcc --version“ .

Hi, message is as follow:
jd@in_dev_docker:/jdx/osqp-cuda-1.0/build/out$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130


nvidia binary driver-version 410.78 from nvidia-410 is installed

**Comment by micschub** [comment]
I also need to know your GPU model.

**Comment by jiesky** [comment]
> I also need to know your GPU model.

Quadro K620

**Comment by micschub** [comment]
Try to compile with “-DDFLOAT=ON“.

**Comment by jiesky** [comment]
@gbanjac @micschub Execuse me. I ran `osqp_demo` succesfully on another computer. And my code works well when CUDA_SUPPORT=OFF on osqp-cuda-1.0, time consuming 20ms, but when i set CUDA_SUPPORT=ON, reinstall..., and then i run same code , GPU Proportion 60%,   time consuming 900ms.
Is there any way to reduce the optimization time and GPU ratio? Ｔｈａｎｋｓ！

**Comment by micschub** [comment]
Can you send us the console output?

**Comment by gbanjac** [comment]
I think your original issue is resolved now so I would suggest closing it. You can use our [forum](https://osqp.discourse.group/) for questions on the timings you obtain with the GPU.

**Comment by jiesky** [comment]
ok, thanks
