### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [oxfordcontrol/osqp#223]
Hi, thanks for this awesome library! Just wanted to let you know that I created [Ruby bindings](https://github.com/ankane/osqp) for it.

The C API was really easy to follow, and the precompiled shared libraries made packaging a breeze 🎉

If you have any feedback, let me know or feel free to create an issue in the project. Thanks!

**Comment by goulart-paul** [comment]
Many thanks for building this interface.   Would you be happy for us to link to it as a third-party supported OSQP interface on our documentation pages?

**Comment by ankane** [comment]
Hey @goulart-paul, that'd be great.

**Comment by bstellato** [comment]
This is great! Thanks a lot @ankane and apologies for the delay. I have just made a PR to mention it in the documentation.

**Comment by ankane** [comment]
Awesome, thank you both! I'm subscribed to releases on GitHub, so will do my best to keep it up-to-date as new versions come out.
