### ISSUE TITLE
Quadratic programming solver providing solutions that violate inequality constraints

### ISSUE THREAD

**Issue by rodrigo-romano** [oxfordcontrol/osqp#225]
While using the osqp solver to implement a predictive controller, in some case it came up with solutions that violate the inequality constraints. A python that reproduces the problem is as follows.

import pickle
import osqp

\# Test files can be found attached in the zip file QPtest_files.zip
filename = 'QPtest1.pickle'
with open(filename, 'rb') as f:
    QPdt = pickle.load(f)
QPdt.keys()

qpp = osqp.OSQP()
qpp.setup(P=QPdt['P'], q=QPdt['q'], A=QPdt['Ain'],
          l=QPdt['lb'],u=QPdt['ub'],
          warm_start=True)
X = qpp.solve()

\# Check for constraint violations
print('True indicates that the corresponding entry violated the constraints:')
(X.x < QPdt['lb'])|(X.x > QPdt['ub'])

Is there an issue related to it or I'm doing something wrong? Thanks in advance!

[QPtest_files.zip](https://github.com/oxfordcontrol/osqp/files/3888992/QPtest_files.zip)

**Comment by goulart-paul** [comment]
By how much are the constraints being violated and what tolerance settings are you using?

**Comment by rodrigo-romano** [comment]
My bad, sorry. I was using the default tolerances (1.0e-03), which were not compatible with my application. I've just decreased eps_abs/eps_rel and there are no constraint violations.
Thank you very much for the assertive prompt reply.
