### ISSUE TITLE
MPC Set up

### ISSUE THREAD

**Issue by LucosidE** [oxfordcontrol/osqp#227]
Hello, 

This is a question and not an issue. 

In the MPC example the state is set up as [x0 x1 .. xk u0 .. uk-1] the cost is block diagonally stacked Q and R matrices and the constraint matrix is such that Ax0 + Bu0 - x1 =0.

The typical way I have seen MPC set up is entirely in terms of the control vector. 
|x1| = |B 0 0 0 ..                | |u0| + |A|    x0
|x2|    |AB 0 ...                   | |u1| + |A^2|x0
|xk|    |A^k-1B A^k-2..   B| |uk| + |A^K|x0

Then the entire horizon cost can be expressed as a quadratic function of u only and the dynamics represented by A and B are incorporated into it. 

Is there a reason why the example uses A and B as constraints instead of the above? Does it result in faster computation?

Thanks 
Vlad

**Comment by goulart-paul** [comment]
Eliminating the states from your problem will reduce the number of variables but make all of the data matrices much less sparse.  For most problems, keeping everything sparse will produce shorter computation times even though there are more variables.

Another consideration is that, for an unstable `A`, taking powers `A^k` is likely to lead to ill-conditioning.

**Comment by LucosidE** [comment]
Thanks for your quick reply Paul.

I got MPC working with both formulations and for my particular problem reducing the number of variables performs a little faster. I think this is because my cost is not temporally independent, the large Q matrix representing cost over the entire horizon is always 50% non zero entries. Representing everything in terms of u leads to the same number of non zero cost elements but significantly fewer constraints. 

OSQP is absolutely fantastic, I am able to achieve 1KHz MPC on a 7 DOF robotic arm. 

Regards
Vlad
