### ISSUE TITLE
solved inaccurate

### ISSUE THREAD

**Issue by stdpython** [oxfordcontrol/osqp#228]
iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   1.90e+01   2.05e+01   1.00e-01   5.59e-04s
 200   9.8793e+01   3.46e+00   3.29e-01   6.63e-01   1.26e-03s
 400   5.8671e+02   6.99e-01   4.47e-01   3.64e+00   1.26e-03s
 600   1.0093e+03   5.03e-01   3.63e+00   1.89e+01   9.08e-04s
 800   1.6476e+03   2.54e-01   1.32e+00   1.89e+01   3.80e-03s
1000   1.9295e+03   1.70e-01   8.04e-01   1.89e+01   6.64e-03s
1200   2.0973e+03   1.22e-01   4.39e-01   1.89e+01   9.46e-03s
1400   2.2233e+03   1.22e-01   3.36e-01   1.89e+01   1.29e-02s
1600   2.3195e+03   1.22e-01   2.55e-01   1.89e+01   1.60e-02s
1800   2.4242e+03   1.22e-01   3.12e+00   9.55e+01   1.39e-03s
2000   2.5917e+03   1.22e-01   2.37e+00   9.55e+01   4.42e-03s
2200   2.6407e+03   1.22e-01   1.06e+00   9.55e+01   7.39e-03s
2400   2.6614e+03   1.22e-01   4.64e-01   9.55e+01   1.02e-02s
2600   2.6750e+03   1.22e-01   1.83e-01   9.55e+01   1.31e-02s
2800   2.6871e+03   1.22e-01   7.92e-02   9.55e+01   1.59e-02s
3000   2.7350e+03   1.22e-01   5.79e-01   4.84e+02   2.38e-03s
3200   2.8377e+03   1.22e-01   7.96e-01   4.84e+02   5.24e-03s
3400   3.0671e+03   1.22e-01   3.87e-01   2.51e+03   9.11e-04s
3600   4.4902e+03   1.22e-01   7.74e+00   2.51e+03   4.60e-03s
3800   6.8278e+03   1.22e-01   8.05e+00   2.51e+03   7.88e-03s
4000   9.9895e+03   1.22e-01   4.63e-01   2.51e+03   1.09e-02s

status:               solved inaccurate
number of iterations: 4000
optimal objective:    9989.4583
run time:             1.10e-02s
optimal rho estimate: 7.58e+03

is there anyone can help me out?
in which situation will lead "solved inaccurate"?

**Comment by goulart-paul** [comment]
"Solved inaccurate" means that you hit the maximum iteration limit, after which the solver checked one final time for convergence with looser tolerances than you requested (I think they are multiplied by 10).   The solution available seemed correct given these looser tolerances, so that is what was returned.
