### ISSUE TITLE
Get any solution (not optimal)

### ISSUE THREAD

**Issue by theocnrds** [oxfordcontrol/osqp#229]
Is there a chance to get OSQP return any solution that meets the constraints, even if it's not the optimal one? For my problem I don't really care about the value of the objective function as long as the solution is within the borders. 
I'm working with cvxpy btw.

Thank you!

**Comment by goulart-paul** [comment]
You can just set 'P=0' and 'q=0' for the objective.

**Comment by theocnrds** [comment]
Okay, pretty obvious and working. I tried that option some time ago but it wasn't working (due to some other bug apparently) and I haven't tried it again since then.

Thanks for the reminder!
