### ISSUE TITLE
cross-compilation for OSQP and compile with static link library

### ISSUE THREAD

**Issue by BaymaxArnO** [oxfordcontrol/osqp#230]
In the CMakeLists.txt, I noticed that whether EMBEDDED is turned on affects osqp_src and osqp_headers.

Now I compile osqp lib on a PC with Linux system by a cross-compilation toolchain，should I add “set(EMBEDDED ON)” in every CMakeLists.txt (include the CMakeLists.txt for qdldl) ?

And what other changes should I make in the CMakeLists.txt?

-----------------------------------------------------------------------------------------------

OK,I have solved the above problem. But, there is another problem when I compile my_test project with libosqp.a.

//
This is console output information:
/home/arno/my_test/osqp_lib/libosqp.a(lib_handler.c.o): In function `lh_load_lib':
lib_handler.c:(.text+0x14): undefined reference to `dlopen'
lib_handler.c:(.text+0x4b): undefined reference to `dlerror'
/home/arno/my_test/osqp_lib/libosqp.a(lib_handler.c.o): In function `lh_unload_lib':
lib_handler.c:(.text+0xc5): undefined reference to `dlclose'
/home/arno/my_test/osqp_lib/libosqp.a(lib_handler.c.o): In function `lh_load_sym':
lib_handler.c:(.text+0x11c): undefined reference to `dlsym'
lib_handler.c:(.text+0x124): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/my_test] Error 1
make[1]: *** [CMakeFiles/my_test.dir/all] Error 2
make: *** [all] Error 2
root@ubuntu:/home/arno/my_test/build# 
//

//
This is my CMakeLists:
cmake_minimum_required(VERSION 3.2)

project(my_test)

set(CMAKE_BUILD_TYPE "Release")

set(CMAKE_C_FLAGS "-static ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-static ${CMAKE_CXX_FLAGS}")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -Wall -O3")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -O3 ")

add_definitions(-std=c++11)

aux_source_directory (${PROJECT_SOURCE_DIR}/src SRC_LIST)

include_directories (${PROJECT_SOURCE_DIR}/include)

include_directories(${PROJECT_SOURCE_DIR}/osqp_lib)

link_directories(${PROJECT_SOURCE_DIR}/osqp_lib)

add_executable (my_test ${SRC_LIST})

target_link_libraries(my_test libosqp.a)

set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)
//

I force the compiler to compile my project using static link library libosqp.a, but I don't know why this static link library have several dynamic linking functions.
Can you give me some suggestions or solutions?

**Comment by imciner2** [comment]
You need to compile with `-DEMBEDDED=` defined to either 1 or 2 to fix that error. The `dlopen` function is used to allow loading of the Paradiso solver on desktop environments, but it is removed for embedded code since the only solver currently supported there is QDLDL (which will be statically linked inside libosqp.a already).

**Comment by BaymaxArnO** [comment]
Thanks for imciner2's reply!
Actually, I have already run my test project with osqp dynamic link library on a 64-bit embedded platform, and none of the test results were abnormal. 
Therefore, I want to keep some features (especially POLISH) when running on embedded platform, at the same time I want to compile my test project using static link library, what should I do to remove Pardiso solver from osqp lib?

**Comment by gbanjac** [comment]
Have you tried to compile with `-DENABLE_MKL_PARDISO=OFF`?

**Comment by BaymaxArnO** [comment]
`-DENABLE_MKL_PARDISO=OFF` is an excellent solution. Thanks very much for gbanjac's reply!
