### ISSUE TITLE
How to Insert Initial Guess to osqp solver

### ISSUE THREAD

**Issue by hxlee309** [oxfordcontrol/osqp#236]
Hi,

I am using osqp to solve a single-input MPC problem, and my control horizon is 5, which means I need to optimize these 5 variables to minimize the total cost. I think using the previous controller input as the initial guesses of the solution may facilitate the solving process. May I know how to insert that into the solver?

Thanks,

Hanxiang

**Comment by gbanjac** [comment]
OSQP sets both primal and dual internal variables to the previously computed solution. Therefore, if you update your initial state in MPC with `update` functions (see [here](https://osqp.org/docs/examples/update-vectors.html) for an example), then warm starting is performed automatically (assuming the `warm_start` setting is set to 1).

Alternatively, you can always use the [warm start functions](https://osqp.org/docs/interfaces/cc++#warm-start) to set the initial iterates to preferred values.

Btw, for questions on how to use OSQP please use our [forum](https://osqp.discourse.group/).

**Comment by hxlee309** [comment]
Thanks for the quick reply! May I know what's the difference between primal and dual variables?

**Comment by gbanjac** [comment]
Primal variables are optimization variables in your problem (control input) and dual variables are Lagrange multipliers associated to the constraints.
