### ISSUE TITLE
Requirement for the P matrix

### ISSUE THREAD

**Issue by hxlee309** [oxfordcontrol/osqp#237]
Hi,

On the website [](https://osqp.org/docs/interfaces/cc++#), I notice that it is required for the P matrix to be upper triangular when we use the "osqp_update_P" function. I have two questions:
1. Does the osqp solver only work for upper triangular P matrix?
2. What should I update my P matrix in the OSQPWorkspace if it is not upper triangular?

Thanks,

Hanxiang

**Comment by goulart-paul** [comment]
P should be a symmetric positive definite matrix, and you should provide OSQP with only the elements in its upper triangle.

**Comment by hxlee309** [comment]
If I use "DenseToCSCMatrix" to convert P from Eigen::MatrixXd to c_float*, is P already satisfied the input requirement?

**Comment by gbanjac** [comment]
Please use our [forum ](https://osqp.discourse.group/) for questions on how to use OSQP.
