### ISSUE TITLE
Different results for running twice

### ISSUE THREAD

**Issue by Simons-star** [oxfordcontrol/osqp#239]
I got different results when I run the code twice, it didn't happen every time, but randomly happen, especially the question is simple, here is the different one, I am sure the input is totally same. But it maybe different when I run it again... I am not sure which part cause this, a) some rand ? b) the iteration time? It happens when the variables is smaller. c) related to running using multi-core ?

-----------------------------------------------------------------
           OSQP v0.4.1  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2018
-----------------------------------------------------------------
problem:  variables n = 933, constraints m = 1246
          nnz(P) + nnz(A) = 4665
settings: linear system solver = qdldl,
          eps_abs = 1.0e-10, eps_rel = 1.0e-06,
          eps_prim_inf = 1.0e-06, eps_dual_inf = 1.0e-06,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off

iter   objective    pri res    dua res    rho        time
   1  -8.9565e+00   3.67e+00   2.97e+01   1.00e-01   1.04e-03s
 200   2.1122e-03   2.12e-05   3.49e-07   1.29e+00   6.08e-03s
 400   2.1169e-03   8.27e-07   1.37e-08   1.29e+00   1.11e-02s

status:               solved
number of iterations: 400
optimal objective:    0.0021
run time:             1.11e-02s
optimal rho estimate: 1.09e+00

-----------------------------------------------------------------
           OSQP v0.4.1  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2018
-----------------------------------------------------------------
problem:  variables n = 933, constraints m = 1246
          nnz(P) + nnz(A) = 4665
settings: linear system solver = qdldl,
          eps_abs = 1.0e-10, eps_rel = 1.0e-06,
          eps_prim_inf = 1.0e-06, eps_dual_inf = 1.0e-06,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off

iter   objective    pri res    dua res    rho        time
   1  -8.9565e+00   3.67e+00   2.97e+01   1.00e-01   9.50e-04s
 200   2.1017e-03   4.99e-05   3.48e-07   8.60e-01   5.98e-03s
 400   2.1125e-03   5.36e-06   3.93e-08   8.60e-01   1.10e-02s
 575   2.1135e-03   8.03e-07   5.86e-09   8.60e-01   1.53e-02s

status:               solved
number of iterations: 575
optimal objective:    0.0021
run time:             1.54e-02s
optimal rho estimate: 1.09e+00

**Comment by Simons-star** [comment]
You can see the first iteration is totally same, so it confuse me a lot, I just want to know why and which part of your code can possibly cause this difference ?

**Comment by bstellato** [comment]
Which OS are you using? Which language? Could you please provide a minimal working example to help us reproduce your results? 

Also, I suggest you to update OSQP to the latest version. It looks like you are using an older one.

**Comment by Simons-star** [comment]
Its ubuntu and C++, I think it not very easy for me to have a working example(I may try later), I just want to know, do you have anything in this program that can possibly lead to different results in different runnigs? Or can you confirm that no anything about random number or something else may cause random results ?

**Comment by goulart-paul** [comment]
See [here](https://osqp.discourse.group/t/same-input-but-slightly-different-solution/69/3):

@bstellato: we should make this a FAQ or something.

**Comment by Simons-star** [comment]
oh great !!! that' what I need, thanks a lot!! 
Btw how can I set rho update interval to a fixed value ? I tried but haven't found where to set this.

**Comment by Simons-star** [comment]
oh I found it, seems to be "work->settings->adaptive_rho_interval = ***"

**Comment by goulart-paul** [comment]
Yes, I think that's the one.

**Comment by goulart-paul** [comment]
> > See [here](https://osqp.discourse.group/t/same-input-but-slightly-different-solution/69/3):
> > @bstellato: we should make this a FAQ or something.
> 
> Hi. This link no longer works. I think I'm having the same/similar issue (see #583) as the person here. Do you mind reposting the link? thanks

I think the issue is that that forum no longer exists.   I will reply with a solution in the initial issue you opened though.
