### ISSUE TITLE
Julia installation instructions do not work

### ISSUE THREAD

**Issue by lostella** [oxfordcontrol/osqp#24]
Hello and congratulations on this very nice software package! I followed the instructions on how to install the Julia interface to the solver, but it looks like `OSQP.jl` is not yet a registered package.
I suppose the correct procedure should be that of issuing
```
Pkg.clone("https://github.com/oxfordcontrol/OSQP.jl.git")
```
rather than using `Pkg.add`.

**Comment by bstellato** [comment]
Hi! Thank you for using OSQP!

OSQP is already a registered package in [METADATA.jl](https://github.com/bstellato/METADATA.jl/tree/metadata-v2/OSQP). 

Which version of Julia are you using? With Julia 0.6 it should download and install without any problems. No need to use `Pkg.clone`.

**Comment by lostella** [comment]
Woops, my bad, my METADATA was probably out of date. Everything working as expected.

Keep up the good work!
