### ISSUE TITLE
Feature proposal: Non-linear User-defined functions

### ISSUE THREAD

**Issue by Capri2014** [oxfordcontrol/osqp#25]
OSQP performance is great! One thing that would be nice to have: Can it support non-linear user-defined functions directly? Like Julia do?

Examples, constrains like: o[1] == p[1] * (ti[1]^p[4]) + p[2] * ti[1] + p[3]

**Comment by bstellato** [comment]
OSQP can be called from [CVXPY 1.0](https://cvxgrp.github.io/cvxpy/index.html) or [YALMIP](https://yalmip.github.io/) which support a more flexible interface.

The Julia interface is already available. We are planning to integrate it with JuMP once the [MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl) is complete and will replace the old MathProgBase. With JuMP you will be able to add expressions as you mentioned.

However, OSQP can solve only convex QPs and LPs. You can have only convex quadratic or linear expressions in the cost and linear constraints.
