### ISSUE TITLE
can P indefinite if QP feasible ?

### ISSUE THREAD

**Issue by yuxaij** [oxfordcontrol/osqp#251]
I have something like P = D - FF^T where the quadratic P is definite and D is diagonal and rank(F) << rank(D). adding constraint y = Fx gives a diagonal P' = diag(D, -1) which is indefinite, while the original problem is apparently solvable.

Does osqp guarantee the convergence in this case?

**Comment by gbanjac** [comment]
No, it does not. OSQP requires that `P` is positive semidefinite.
