### ISSUE TITLE
Detecting infeasibility conditions somewhat broken

### ISSUE THREAD

**Issue by bodono** [oxfordcontrol/osqp#255]
In discussion with @goulart-paul he suggested I open an issue for this.

The infeasibility / unboundedness detection scheme is highly counter-intuitive, in that neither reducing nor increasing eps_prim_inf yields more accurate certificates because the two places it is used have differing interpretations. Moreover, and more seriously, it means that for some infeasible problems there does not exist a certificate for some choices of eps_prim_inf. For example, this scalar problem:

import cvxpy
x = cvxpy.Variable()
obj = cvxpy.Minimize(x)
prob = cvxpy.Problem(obj, [x <=0, x >= 1e-4])

is trivially infeasible, but OSQP can never solve it and will run without terminating forever. Bizarrely reducing eps_prim_inf can solve it, which is counter-intutive to the user. But for any choice of eps_prim_inf there is a simple scalar problem that is infeasible that OSQP cannot solve (just replace 1e-4 with eps_prim_inf in the above problem).

Possibly the negativity test can be replaced with a strict inequality test.

**Comment by gbanjac** [comment]
I agree that the current implementation is not correct. I think that `-eps_prim_inf` in [this condition](https://github.com/oxfordcontrol/osqp/blob/master/src/auxil.c#L409) should be replaced with `eps_prim_inf`. The same should be done in [this dual infeasibility condition](https://github.com/oxfordcontrol/osqp/blob/master/src/auxil.c#L466).

I also see that the termination criterion is correct in the [MPC paper](https://link.springer.com/content/pdf/10.1007/s12532-020-00179-2.pdf) (Section 3.4), but not in the [arxiv preprint](https://arxiv.org/pdf/1711.08013v3.pdf).

**Comment by bstellato** [comment]
Thank you @bodono for pointing this out. We, indeed, discussed how to change it and the final paper manuscript is correct. The [latest version on arxiv](https://arxiv.org/pdf/1711.08013.pdf) is also correct.

@gbanjac's PR #256 should fix this. It should fix also https://github.com/oxfordcontrol/osqp/issues/180

**Comment by gbanjac** [comment]
Oops. Sorry, I didn't realized I used an old link.

**Comment by bstellato** [comment]
Should be fixed now in `develop-0.x` branch. Feel free to reopen it if not.
