### ISSUE TITLE
Different P and A sizes cause Matlab to crash

### ISSUE THREAD

**Issue by msvec94** [oxfordcontrol/osqp#262]
When passing matrices P ([n x n]) and A ([m x n_1]) to problem setup function, if one accidentally defines matrix A in a way that n_1 != n (false optimizer size), Matlab crashes instead of reporting an error. In case no one reported it earlier, I think this is something which could easily be fixed and would improve the usability of the software.

**Comment by gbanjac** [comment]
Thanks for reporting the issue. Can you please open it in the [osqp-matlab](https://github.com/oxfordcontrol/osqp-matlab) repo instead?
