### ISSUE TITLE
Improving Solver Execution time on aarch64 

### ISSUE THREAD

**Issue by Ajin2305** [oxfordcontrol/osqp#267]
I currently am coding the solver on C on a amd64 machine and then cross compiling on aarch64 (Nvidia AGX) type machine. I wish to optimise to run it faster on this CPU. I wanted to know if there are solutions already available to improve the efficiency without actually compromising the structure of problem and performance.  

I did see the post on using CUDA and running the solver on GPU. But i initially want to exhaust my options with CPU. My code has no issues running in real-time on my Personal Computer which is i7-7th gen mobile processor ( should be faster) compared to the target that ARMv8.2‑A

**Comment by goulart-paul** [comment]
The biggest component of execution time by far is in the linear solver code, which includes both an initial matrix factorisation and then a forward/backward substitution using that factorisation at every time step.

If you wish to make some platform-specific optimisation, I would suggest starting there.   The main OSQP package comes with interfaces to both QDLDL and MKL Pardiso out of the box, but you can also use another solver if you [write your own interface](https://osqp.org/docs/contributing/index.html#interfacing-new-linear-system-solvers) to it.    If you have some more efficient custom linear solver for your platform, I would suggest using that.   The QDLDL code is also open source, so you could perhaps modify that instead.  

Version 1.0 of OQSP will allow for customisation of all of the other linear algebra steps in the code as well, i.e. the basic BLAS type operations, projection etc.   Modifying those operations also offers potentially substantial speedups if you are willing to get into the weeds of your computing architecture.   The v1.0 code is available now, although probably very unstable and certainly not supported yet.

**Comment by Ajin2305** [comment]
Thanks for the tip. I shall look into it.

**Comment by Ajin2305** [comment]
I also wanted to know if the GPU solver implemented is stable?

**Comment by goulart-paul** [comment]
Perhaps better to ask that question [here](https://github.com/oxfordcontrol/cuosqp).

**Comment by Ajin2305** [comment]
Update : I found the cause for the solver to take more time, this is because of an ILL -Conditioned Px matrix, with its min eigen value being close to 1-e7. Is there any option in solver that can help with this?.
 As of now one of our ideas is to tackle this with damping matrix coefficient that is added to the diagonal of the Px. But that influences the solution quality. Let me know if there are any suggestion on the solver end. Thanks :)

**Comment by Ajin2305** [comment]
@goulart-paul  Is there auto-scaling option that I can use for my problem?
