### ISSUE TITLE
[openSUSE] Skip compiling internal qdldl when qdldl dependency already install? 

### ISSUE THREAD

**Issue by kevinsmia1939** [oxfordcontrol/osqp#269]
Hello,

I am trying to package osqp and qdldl.
I found that osqp without bundled qdldl submodule (and probably others submoldules) does not able to compile.

I tried packaging qdldl separately, then package osqp (without bundle) with qdldl as dependency. ospq could not detect install qdldl.

Do you think it is better to just package osqp with qdldl bundle or use qdldl separately?

Thank you.

**Comment by traversaro** [comment]
Hi @kevinsmia1939, we had a related discussion in https://github.com/oxfordcontrol/osqp/issues/85 . As far as I remember, for various reason only the use of the internal qdldl was supported, but I do not know if this is still the case now.

**Comment by kevinsmia1939** [comment]
> Hi @kevinsmia1939, we had a related discussion in #85 . As far as I remember, for various reason only the use of the internal qdldl was supported, but I do not know if this is still the case now.

I think it is still the case, I could not figured out how to make osqp use external qdldl.
I think I might have to try package osqp with bundled qdldl for now.
Thanks.
