### ISSUE TITLE
Problem reaching maximum iteration

### ISSUE THREAD

**Issue by Ajin2305** [oxfordcontrol/osqp#276]
While using the solver, I observed that  at times the solver reaches max iterations (status val 2 & -2) causing the run time to increase by large amount as observed in the figures. I extracted the input vector and matrices and the mex solver to recreate the problem (First instance of status val -2).  Why does this happen ? What can I do to tackle this?

![solver_runtime](https://user-images.githubusercontent.com/31613200/97436932-0e560400-1923-11eb-9e77-603844c67411.jpg)
![solver_statval](https://user-images.githubusercontent.com/31613200/97436935-0eee9a80-1923-11eb-8abf-32d5aa843e1b.jpg)

[Data.zip](https://github.com/oxfordcontrol/osqp/files/5451762/Data.zip)

**Comment by goulart-paul** [comment]
It appears that that zip file you attached has an embedded solver generated by osqp compiled for windows, which I can't test directly.   However, if I do this using your problem data:

```
load("status_val_minus2_dataset.mat") 
m = osqp;
m.setup(Px,q,Ax,low,upp);
m.solve()
```

Then OSQP returns a solution in 75 iterations.      

It seems from your figure that you are running the solver many times, presumably with different values for the linear or matrix-valued terms.    Are you warm-starting the solver between the different problem instances?   If so, it could be the case that a single bad instance (e.g. an infeasible problem) causes the primal or dual variables of the solver to end up with weird (probably large) values, making the next problem instance take too long to converge.   

If this is the case, I would suggest resetting all of the internal variables (using the 'warm_start' method) back to zero.

**Comment by goulart-paul** [comment]
Related issue opened [here](https://github.com/oxfordcontrol/osqp-matlab/issues/29).

**Comment by Ajin2305** [comment]
My bad here is the setup I use:
prob.setup(sparse(triu(Px+Px')), q, sparse(Ax), low, upp,'eps_abs',1e-8,'eps_rel',1e-8,'adaptive_rho_interval',25,'max_iter',20000);

**Comment by goulart-paul** [comment]
In that case I think the problem is almost certainly that your tolerance values are extremely tight for an ADMM-based solver like OSQP.   You are likely to have much better success with something like 1e-4 relative tolerance.

**Comment by Ajin2305** [comment]
Thanks that does help in a way 👍🏼 . I also had to scale my problem to tackle the huge condition number Px Matrix had.
