### ISSUE TITLE
Can I use osqp on 64-bit Windows with 32-bit QT?

### ISSUE THREAD

**Issue by Tengyun-Mo** [oxfordcontrol/osqp#278]

**Comment by Tengyun-Mo** [comment]
I got an error when I use cmake to configure osqp
`C:\Users\91678\Desktop\osqp-master\osqp-master\lin_sys\direct\qdldl\CMakeLists.txt:2: error: The source directory C:/Users/91678/Desktop/osqp-master/osqp-master/lin_sys/direct/qdldl/qdldl_sources does not contain a CMakeLists.txt file.`

**Comment by goulart-paul** [comment]
The QDLDL solver is included as a submodule.   You need to do something like ``git submodule update --init --recursive`` within your OSQP repo to get it.
