### ISSUE TITLE
why i set a hard problem, it can be solved, while i set a very easy problem(0,0,0,0,0,.....), it cant be solved , and the estimate get larger and larger

### ISSUE THREAD

**Issue by Richard-LXA** [oxfordcontrol/osqp#279]
iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   1.00e+00   1.40e+12   1.00e-01   4.63e-04s
 200   1.2286e+11   2.24e+00   9.29e+10   5.14e-01   1.47e-03s
 400   1.1636e+11   2.24e+00   2.62e+11   2.91e+00   2.34e-03s
 600   1.2547e+11   2.24e+00   9.66e+10   2.91e+00   3.17e-03s
 800   1.1924e+11   2.24e+00   2.94e+11   2.91e+00   3.97e-03s
 975   1.0000e+20   2.24e+00   3.04e+11   2.91e+00   4.68e-03s

status:               primal infeasible
number of iterations: 975
run time:             4.70e-03s
optimal rho estimate: 4.29e+00

[OsqpEigen::Solver::solve] The solution is unfeasible.

**Comment by gbanjac** [comment]
The status 'primal infeasible' means that your QP has no feasible point. The estimates grow unbounded because iterates of the numerical method used in OSQP diverge when facing an infeasible problem.

**Comment by Richard-LXA** [comment]
> The status `primal infeasible` means that your QP has no feasible point. The iterates grow unbounded because iterates of the numerical method used in OSQP diverge when facing an infeasible problem.

but the answer is all zero ,why it cant be solved?

p.s. im doing motion planning and do it in X_axis and Y_axis , my X_axis solved perfect , but Y_axis will face this problem

**Comment by gbanjac** [comment]
Can you post a MWE? If you are using osqp-eigen, then please post your issue in [this repository](https://github.com/robotology/osqp-eigen).

**Comment by Richard-LXA** [comment]
> Can you post a MWE? If you are using osqp-eigen, then please post your issue in [this repository](https://github.com/robotology/osqp-eigen).

yes im using osqp-eigen,  emmm, what is MWE

**Comment by gbanjac** [comment]
A minimal working example, i.e., a code snippet that one can run to reproduce your issue.

**Comment by gbanjac** [comment]
The issue seems to be posted in [osqp-eigen](https://github.com/robotology/osqp-eigen) in [this issue](https://github.com/robotology/osqp-eigen/issues/76).
