### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by microprediction** [oxfordcontrol/osqp#287]
on this page: https://github.com/oxfordcontrol/osqp/tree/cuda-1.0

Linux: cmake -G "Unix Makefiles" -DDLONG=OFF -DDFLOAT=ON -CUDA_SUPPORT=ON .. to configure and cmake --build . to build.

should read  DCUDA_SUPPORT

**Comment by gbanjac** [comment]
Fixed in https://github.com/oxfordcontrol/osqp/commit/41402bb2b5305996f0fbae885461bfcc3414152e
