### ISSUE TITLE
Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex

### ISSUE THREAD

**Issue by lilintong22222** [oxfordcontrol/osqp#288]
I have two inputs，only the P matrix is different：
1. P1 only have diagonal elements
2. P2  have the same diagonal elements with P1，and also have some nonzero elements at（i, i+1）

when I input P1，osqp will output a result，but when I input P2，osqp setup failed

Error Detail：
> factor_status: 2704, nvar: 3003 
> ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
> ERROR in osqp_setup: Linear systems solver initialization failure
> ERROR in osqp_solve: Workspace not initialized

Error Code：
https://github.com/oxfordcontrol/osqp/blob/e2b6fdbe9df743a790db774fe33a921c0804da91/lin_sys/direct/qdldl/qdldl_interface.c#L82

**I don't know exactly why？maybe because P2 is not positive semi-definite matrix ？**

**Comment by goulart-paul** [comment]
Yes, almost certainly because in the second case your matrix is not positive semidefinite.

**Comment by lilintong22222** [comment]
I use the Eigen library to confirm that P2 is a positive semidefinite matrix
![image](https://user-images.githubusercontent.com/7465438/108822778-81823500-75fa-11eb-9559-d2a084892195.png)

What is the semantic meaning of "Number of positive elements of D should be equal to nvar"
https://github.com/oxfordcontrol/osqp/blob/e2b6fdbe9df743a790db774fe33a921c0804da91/lin_sys/direct/qdldl/qdldl_interface.c#L80-L83

**Comment by goulart-paul** [comment]
> What is the semantic meaning of "Number of positive elements of D should be equal to nvar"

We factor the KKT matrix `K = [P + \sigma I, A^T; A, -1/\rho I]` into the product `K = LDL^T`.   K is a quasidefinite matrix with a positive definite block `P + \sigma I` in the top left, and a negative definite block `-1/\rho  I` in the bottom right.    The matrix `D` in the factorisation has the same inertia as the matrix `K`, i.e. it as the same number of positive, negative and zero eigenvalues.   We can therefore check that the matrix `P` is PSD (the value \sigma >0 is very small) by checking that D has exactly `nvar` positive elements.

Can you say what the matrix `P` is here for you?

**Comment by lilintong22222** [comment]
This is my test data：https://drive.google.com/file/d/1E_iFzbMJBQrlXegTuwJOea_gis9nAq_M/view?usp=sharing
It contains `P`, `A` and all other parameters.

**Comment by goulart-paul** [comment]
Your matrix does not appear to be positive semidefinite.   For example, the lower right 2x2 block appears to be
`
[1202.0  -1200.0;
  -1200.0    602.0]
`
which has a negative eigenvalue.

**Comment by lilintong22222** [comment]
Why is it 

> [1202.0  -1200.0
    -1200.0 602.0]

 rather than 

> [1202.0  -1200.0
        0        602.0]

And another data（https://drive.google.com/file/d/1k1XptAvmYc0LPjaisb7akccUXbsWVYsB/view?usp=sharing）also has [1202.0-1200.0; -1200.0 602.0]，but setup osqp success

Maybe the different constraint causes this problem?

**Comment by goulart-paul** [comment]
It is because OSQP assumes that the matrix `P` is symmetric and that you are only providing the upper triangular part.

**Comment by lilintong22222** [comment]
So if my `P` is already upper triangular matrix，I need to check positive semidefinite with `P + P' - diag(diag(P))`  ？

**Comment by goulart-paul** [comment]
Yes

**Comment by lilintong22222** [comment]
Thank you very much！

**Comment by lilintong22222** [comment]
But there is still a question left: why this data（https://drive.google.com/file/d/1k1XptAvmYc0LPjaisb7akccUXbsWVYsB/view?usp=sharing ）`P` is not positive semidefinite, but can setup osqp success ？

**Comment by goulart-paul** [comment]
It is most likely because you are not providing the problem data to OSQP correctly.  At a guess, you are giving the data as a lower triangular matrix and OSQP is ignoring everything in the lower triangle, and therefore your matrix `P` is being interpreted as a diagonal matrix.

Please do some basic checking on your problem formulation before continuing this thread.   For example, try your code on a 2x2 or 3x3 problem where you know the answer and make sure that you are getting expected results.   

As an example of a basic check for the problem I suggest above, make sure that `nnz(P) + nnz(A)` reported in the OSQP output is what you expect it to be.
