### ISSUE TITLE
my matrix P is positive definite， Why OSQP solver report：“problem non convex”

### ISSUE THREAD

**Issue by Whut-Dong** [oxfordcontrol/osqp#291]
I check my matrix P， it's positive definite，but  solver status: problem non convex. who can help me?? sincerely thanks

CODE:
c_float P_x[4] ={ 1.453296402508584e+40, -8.988489094974820e+37, 5.559288256861119e+35, 500, };
  c_int   P_nnz  = 4;
  c_int   P_i[4] = { 0, 0, 1, 2, };
  c_int   P_p[4] = { 0, 1, 3, 4, };
  c_float q[3]   = { -2.924217683974705e+40, 1.808598563890488e+38, 0};

  c_float A_x[5] = { 1, 1, 1, 1, 1, };
  c_int   A_nnz  = 5;
  c_int   A_i[5] = { 0, 3, 1, 3, 2,};
  c_int   A_p[4] = { 0, 2, 4, 5, };
  c_float l[4]   ={ -0.1, -0.1, 0, -0.8744, };
  c_float u[4] = { 0.1, 0.1, 10, 0.8744, };
  c_int n = 3;
  c_int m = 4;
  
   // Problem settings
  OSQPSettings *settings = (OSQPSettings *)c_malloc(sizeof(OSQPSettings));

  // Structures
  OSQPWorkspace *work; // Workspace
  OSQPData *data;      // OSQPData

  // Populate data
  data    = (OSQPData *)c_malloc(sizeof(OSQPData));
  data->n = n;
  data->m = m;
  data->P = csc_matrix(data->n, data->n, P_nnz, P_x, P_i, P_p);
  data->q = q;
  data->A = csc_matrix(data->m, data->n, A_nnz, A_x, A_i, A_p);
  data->l = l;
  data->u = u;
  
  // Define Solver settings as default
  osqp_set_default_settings(settings);

  // Setup workspace
  work = osqp_setup(data, settings);

  // Solve Problem
  osqp_solve(work);

  // Clean workspace
  
  cout << "solution = " << work->solution->x[0]<< endl;

  osqp_cleanup(work);
  c_free(data->A);
  c_free(data->P);
  c_free(data);
  c_free(settings);
``

![23232323323](https://user-images.githubusercontent.com/69831155/110292640-7f6f9b80-8028-11eb-9f41-b20b4c338f3e.png)

**Comment by Whut-Dong** [comment]
I calculate the eigenvalues of matrix P through MATLAB:   500, 2.17177502476502e+26, 1.45335199539113e+40, all positive;
matrix P is :
![343434343](https://user-images.githubusercontent.com/69831155/110288430-f43fd700-8022-11eb-9798-4fecaf5eed54.png)

**Comment by goulart-paul** [comment]
The problem here could be that the values are so huge.   OSQP internally defines OSQP_INF as something like 1e+20.

Your vector `q` is also huge, so I would suggest just scaling down `P` and `q` by a common factor (say 1e+35) an trying again.   .

**Comment by Whut-Dong** [comment]
That accounts for it,  thank you very much for your answer, Professor.
