### ISSUE TITLE
Segmentation error with PARDISO

### ISSUE THREAD

**Issue by JOHN194872** [oxfordcontrol/osqp#292]
Hi,
I get a segmentation error after a partial run:
Statistics:
===========
 < Parallel Direct Factorization with #cores: >              1
 <                                and #nodes: >              1
 < Numerical Factorization with Level-3 BLAS performance >

 < Linear system Ax = b>
             #equations:                                     8
             #non-zeros in A:                                18
             non-zeros in A (%):                             28.125000
             #right-hand sides:                              1

< Factors L and U >
             #columns for each panel:                        80
             # of independent subgraphs:                     0
 < preprocessing with state of the art partitioning metis>
             #supernodes:                                    5
             size of largest supernode:                      4
             number of nonzeros in L                         29
             number of nonzeros in U                         1
             number of nonzeros in L+U                       30
             number of perturbed pivots                      0
             number of nodes in solve                        8
             Gflop   for the numerical factorization:        0.000000
             Gflop/s for the numerical factorization:        0.000067

Factorization completed ...
./runfile: line 14: 23676 Segmentation fault      (core dumped) ./pardiso_sym

This is my compilation command:
gcc -g -o pardiso_sym pardiso_sym.c -L. -lpardiso600-GNU800-X86-64  -llapack -lrefblas -lgfortran  -fopenmp -lpthread -lstdc++ -lm

Please help

**Comment by goulart-paul** [comment]
It seems like this is purely a pardiso problem and is not happening within OSQP.  Is that right?

**Comment by JOHN194872** [comment]
You are right - I am just hoping that someone can help.

**Comment by goulart-paul** [comment]
No idea, but I would suggest trying the question on the intel MKL forum instead (which I think you have just done).

**Comment by JOHN194872** [comment]
Yes I have but thank you for your interest.
Regards,
John
