### ISSUE TITLE
Building from source with Python bindings (in a conda environment)

### ISSUE THREAD

**Issue by Neotriple** [oxfordcontrol/osqp#297]
Hi there,

I'm trying to build from source while also building the python bindings. The reason I'm attempting to do this is to find out the number of times the QDLDL_solve functionality is called during a particular solve. 

When I attempt to build from source, I run into this issue:

```
[  5%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o
cc1: warning: /home/pshah/anaconda3/envs/osqp_test/bin/python: not a directory
In file included from /home/pshah/Applications/osqp/include/types.h:8:0,
                 from /home/pshah/Applications/osqp/include/lin_alg.h:9,
                 from /home/pshah/Applications/osqp/lin_sys/direct/pardiso/pardiso_interface.h:8,
                 from /home/pshah/Applications/osqp/lin_sys/direct/pardiso/pardiso_interface.c:1:
/home/pshah/Applications/osqp/include/glob_opts.h:44:13: fatal error: Python.h: No such file or directory
 #   include <Python.h>
             ^~~~~~~~~~
compilation terminated.
lin_sys/direct/CMakeFiles/linsys_pardiso.dir/build.make:62: recipe for target 'lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o' failed
make[2]: *** [lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'lin_sys/direct/CMakeFiles/linsys_pardiso.dir/all' failed
make[1]: *** [lin_sys/direct/CMakeFiles/linsys_pardiso.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
```
A quick google makess me think this is because I'm not using python3.X-dev (which should include the python header file). Is it possible to build from source without the python3.X-dev? Alternatively, is there a way to read / find out how many times the QDLDL_solve function is being called?

**Comment by goulart-paul** [comment]
The number of calls to `QDLDL_solve` should just be the number of iterations, plus one if the solver has polishing enabled.

The number of calls to `QDLDL_factor` is also logged (see [here](https://github.com/oxfordcontrol/osqp/blob/0b34f2ef5c5eec314e7945762e1c8167e937afbd/include/types.h#L88) in the C source)

**Comment by Neotriple** [comment]
Thanks for the information!
