### ISSUE TITLE
qdldl sources missing in 0.6.2 release's tar.gz and zip archives

### ISSUE THREAD

**Issue by ThomasLingenau** [oxfordcontrol/osqp#304]
The folder lin_sys/direct/qdldl/qdldl_sources is empty in both archives of the latest release:
https://github.com/oxfordcontrol/osqp/archive/refs/tags/v0.6.2.zip
https://github.com/oxfordcontrol/osqp/archive/refs/tags/v0.6.2.tar.gz

Probably you forgot to add them since they are included via a git submodule. Could you please provide zip or tar.gz archives with the qdldl sources included? I want to provide osqp as a dependency in a big repository via a conan package. Using the archives would just be easier compared to configuring a conan package built from sources.

**Comment by imciner2** [comment]
I have manually uploaded a complete sources archive to the release page for 0.6.2 that includes the QDLDL source code, since I don't think there is a way that GitHub will automatically create one that includes all submodules (even though that would be nice).
