### ISSUE TITLE
Fails to compile without -DPROFILING

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/osqp#33]
The `adaptive_rho_fraction` field is only defined with `PROFILING`:
https://github.com/oxfordcontrol/osqp/blob/2aeaebb3a3f8f718e16373caccb0c5a8e091a004/include/types.h#L146
but it's accessed here:
https://github.com/oxfordcontrol/osqp/blob/2aeaebb3a3f8f718e16373caccb0c5a8e091a004/src/auxil.c#L845
regardless of `PROFILING`.
This is with `/* #undef EMBEDDED */` in `glob_opts.h`.

**Comment by bstellato** [comment]
Ooops! It should be fixed now. Thanks for checking.
