### ISSUE TITLE
Ubuntu 16.04 Cmake 3.10 Python3 codegen update_A(Ax,None,0) fails

### ISSUE THREAD

**Issue by rjibrin** [oxfordcontrol/osqp#36]
I get the following in from the iPython console:
`
An error ocurred while starting the kernel
In file included from ../include/types.h:9:0,
from ../include/osqp.h:9,
from emosqpmodule.c:7:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/ldl.h:10,
from osqp/ldl.c:157:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/osqp.h:9,
from osqp/auxil.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/scaling.h:9,
from osqp/scaling.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/proj.h:8,
from osqp/proj.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/osqp.h:9,
from osqp/osqp.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/ldl.h:10,
from osqp/suitesparse_ldl.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/lin_alg.h:9,
from osqp/lin_alg.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/util.h:8,
from osqp/util.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
In file included from ../include/types.h:9:0,
from ../include/kkt.h:8,
from osqp/kkt.c:1:
../include/constants.h:34:20: warning: ‘LINSYS_SOLVER_NAME’ defined but not used [‑Wunused‑variable]
static const char *LINSYS_SOLVER_NAME[] = {
^
`

**Comment by bstellato** [comment]
Could you please provide a minimal working example for this issue? Does the error happen after or during code generation?

**Comment by rjibrin** [comment]
It turned out that the C code was crashing because I was sending the CSC matrix to update_A, instead of an ndarray.
Since the failure message was nothing relevant, it took me a while to figure it out.
