### ISSUE TITLE
Segmentation fault when turning off verbose printing in Python

### ISSUE THREAD

**Issue by darren-roos** [oxfordcontrol/osqp#39]
Code:
```
import osqp

prob = osqp.OSQP()
prob.update_settings(verbose=False)
```

Output:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Did not expect error.

Ran on OSQP 0.2.1 with Python 3.6.4 installed via Anaconda on Ubuntu 16.04.
Replicated for OSQP 0.2.1 with Python 3.6.4 installed via Anaconda on Mac OS X High Sierra.

**Comment by bstellato** [comment]
This happens when you update the settings or the problem data without performing the setup first. I will fix it.

**Comment by gbanjac** [comment]
Closed via https://github.com/oxfordcontrol/osqp-python/pull/12
