### ISSUE TITLE
allow eps_rel = 0?

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/osqp#40]
OSQP currently enforces that eps_rel be positive:
https://github.com/oxfordcontrol/osqp/blob/515ceba7c72c47ea73f01b136cb729d62ae27dc0/src/auxil.c#L887-L890

Is there a reason to not allow eps_abs positive and eps_rel zero? Many other QP solvers allow you to enforce an absolute tolerance on constraints, so setting eps_rel to zero would help when comparing OSQP to these solvers. Of course, it's possible to set it to an extremely tiny value, but you shouldn't need to do this.

**Comment by bstellato** [comment]
You are right, there is not an explicit reason. I have updated it here b53d5908e093712c7fe0be0150c8b45478c6dedf

**Comment by mlubin** [comment]
Thanks! You may want to add a check that at least one of `eps_abs` and `eps_rel` is positive.

**Comment by bstellato** [comment]
Thanks for the tip. It should be added in the `develop` branch now.
