### ISSUE TITLE
Update the hessian matrix and the linear constraint matrix

### ISSUE THREAD

**Issue by GiulioRomualdi** [oxfordcontrol/osqp#42]
I have seen in your [C/C++ api](http://osqp.readthedocs.io/en/latest/interfaces/CC++.html) that it is possible to update both the hessian matrix `P`and the linear constraint matrix `A` using respectively  the `osqp_update_P()`  and the `osqp_update_A()` methods; however these functions assume that the sparsity structure of the matrices does not change.

If this assumption is no more satisfied is it possible to remove the old matrices and add the new ones?   
I have seen in [your repository](https://github.com/oxfordcontrol/osqp/blob/master/src/osqp.c#L142-L144) that the `linsys_solver` struct depens on `A` and `P` matrices and more specifically the KKT matrix depends on the number of non zero entries in the `A` and `P` matrices (so the `linsys_solver->update_matrices()` method cannot be used for this purpose). Thus my idea is to deallocate the `linsys_solver` struct and instantiate it again with the new matrices.
```c++
...

// Free linear system solver structure
if (work->linsys_solver){
   if(work->linsys_solver->free){
      work->linsys_solver->free(work->linsys_solver);
    }
}

// Free old hessian and linear constraint matrices
csc_spfree(work->data->P);
csc_spfree(work->data->A);

// Allocate new matrices
work->data->P = csc_to_triu(newP); 
work->data->A = copy_csc_mat(newA);

// Instantiate the solver 
work->linsys_solver = init_linsys_solver(work->data->P, work->data->A,
		                         work->settings->sigma, work->rho_vec,
			                 work->settings->linsys_solver, 0);
...
```
What do you think about this approach?  Is there a better way to solve this problem?  
Thank you in advance for any help you can provide.

**Comment by bstellato** [comment]
The main idea why the nonzero elements of  `P` and `A` matrices can be updated without performing a new setup is that in this way we can avoid performing the complete KKT matrix factorization. This consists in two steps: a numeric and a symbolic factorization. If we change only the nonzero elements (and not the sparsity pattern) of the matrices `P` and `A` we can perform only the numeric factorization and thus:

1. Save computation time
2. Avoid dynamic memory allocations (useful for embedded applications)

If you need to change also the sparsity pattern of `P` and `A` a new factorization is required which is the most computationally demanding part of the `setup` phase and requires dynamic memory allocation. I suggest you to throw away the old workspace perform a new `setup` call in the case the sparsity pattern changes. This is basically as efficient as implementing custom of `P` and `A` update functions. Is there a particular reason why you cannot perform the `setup` again in your application?

**Comment by GiulioRomualdi** [comment]
First of all thank @bstellato for your prompt reply. There is no reason why I cannot perform the workspace `setup` again.  So I will follow your suggestion.

**Comment by bstellato** [comment]
Great! Let let me know if you have any issues with that. I will close this for now.

**Comment by zslwyuan** [comment]
> Great! Let let me know if you have any issues with that. I will close this for now.

Hi @bstellato ,
I am very curious about whether the factorization can make use of multi-threading? Since in some scenarios, the factorization in the setup procedure takes up almost 50% of runtime. ^_^
