### ISSUE TITLE
Reaches iteration limit for a simple infeasible problem, when one bound of the constraint is infinity

### ISSUE THREAD

**Issue by hongkai-dai** [oxfordcontrol/osqp#43]
[osqp_demo.zip](https://github.com/oxfordcontrol/osqp/files/1713106/osqp_demo.zip)
Thanks for providing the solver, it's really fast!

I have a question to impose one side of the bound to infinity.

I tried to solve the following problem
```
min x₁² + 2x₂²
s.t x₁ + 2x₂ = 2
     x₁ ≥  1
     x₂ ≥  2
```
Note that one side of the bounds are infinity. The code is attached (I just modified a few entries in examples/osqp_demo.c). The solver reaches iteratation limit, and keeps increasing the weight on the penalty term.

If I change the last two constraints to be upper-bounded by finite numbers, such as
```
2 ≥ x₁ ≥  1
3 ≥ x₂ ≥  2
```
then the solver detects the infeasibility immediately. 

How should I impose constraint with one side of the bounds being infinity?

**Comment by gbanjac** [comment]
Thanks for using OSQP.

Your code is using a macro `INFINITY` which is not defined in the OSQP project. The code should work if you replace `INFINITY` by `OSQP_INFTY` (which is defined in `glob_opts.h`).

**Comment by hongkai-dai** [comment]
Thanks for the prompt reply! Yes using OSQP_INFTY solves the problem
