### ISSUE TITLE
Segmentation fault when turning off scaling and the matrices are updated

### ISSUE THREAD

**Issue by GiulioRomualdi** [oxfordcontrol/osqp#49]
If the number of scaling iteration is set to `0` a segmentation fault occurs when the hessian `P` or/and the linear constraints matrix `A` are updated.
You can verify the issue adding the following line [here](https://github.com/oxfordcontrol/osqp/blob/master/tests/update_matrices/test_update_matrices.h#L102)
```c
settings->scaling = 0;
```

I think that the problem is caused to the calling of the `scale_data()` and `unscale_data()` methods in the `osqp_update_*()` functions. In this case it can be easily solved adding an `if` statement 
```c
if(work->settings->scaling){
    scale_data(work);
}
```

**Comment by bstellato** [comment]
Thank you for letting us know. I will fix it.
