### ISSUE TITLE
naming of set_default_settings

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/osqp#50]
`set_default_settings` is exported from `osqp.h` but is missing the `osqp_` prefix. This name is pretty generic, is there a reason not to prefix it?
Ideally everything defined by including `osqp.h` should have a prefix, but `set_default_settings` is maybe the most prominent candidate because it's part of the public API and is used everywhere.

**Comment by bstellato** [comment]
Yes it totally makes sense. I have changed it in this commit 085f719c369aa248788bf9770640a95678def528. Now it appears in `osqp.h` and it is called `osqp_set_default_settings`.

**Comment by mlubin** [comment]
Thanks!
