### ISSUE TITLE
Error when building Matlab interface

### ISSUE THREAD

**Issue by rrenjie** [oxfordcontrol/osqp#52]
Hi there, I've been receiving the error 

"Could NOT find Matlab (missing: Matlab_MEX_LIBRARY) (found version "9.0")
CMake Error at CMakeLists.txt:220 (message):
  You need Matlab libraries to build the Matlab interface"

when building the Matlab interface (using make_osqp command in Matlab). It seems like CMake cannot find Matlab. Any idea to fix this? Thanks.

**Comment by goulart-paul** [comment]
What is the operating system and matlab version for which you got this error?

**Comment by gbanjac** [comment]
Have you tried to download the precompiled binaries? Have a look at the link below:
http://osqp.readthedocs.io/en/latest/installation/matlab.html

**Comment by rrenjie** [comment]
@goulart-paul I am using 64bit Win10 with Matlab 2016a. However I am good now using the precompiled binaries as suggested by @gbanjac. 
Thank you @gbanjac I've successfully installed osqp using the binaries.
