### ISSUE TITLE
osqp solver in the loop

### ISSUE THREAD

**Issue by yasseryasaei** [oxfordcontrol/osqp#53]
Hi, 

The problem that I have faced is that when I put a quadratic programming optimization in a loop (say for 1000 runs), it does not come back with results for most of the cases. I traced the problem and kept the record of the failures. Surprisingly, when I run the optimization for those failed ones individually, it does not fail, but it fails when in a loop. Also, the failures are not reproducible, meaning that the loop each time come back with different failed cases!

**Comment by bstellato** [comment]
Could you please provide more details on the issue? Which operating system? Language? OSQP version?

It would be great if you could share a minimal working example so that we can reproduce the loop issue.

**Comment by yasseryasaei** [comment]
I am running it on macOS High Sierra version 10.13.3 as a python 3.6 script. The version of osqp is 0.3.0 installed via pip.

In terms of working example, unfortunately I cannot provide my code at this stage. We're working on different solvers and test them to find which of them better suits our needs.

**Comment by yasseryasaei** [comment]
However, I can tell you that I am comparing it with cvxopt and cvxpy.

**Comment by goulart-paul** [comment]
It will be very difficult to diagnose your problem without at least some indication of the type of optimisation problem and usage that actually causes the difficulty, or without a crash report, stack trace, execution log etc.

Could you say generally what it is that you want to change at each iteration of your loop and how you modify the solver data at each iteration?

**Comment by bstellato** [comment]
Also, could you please describe what does "it does not come back with results for most of the cases" mean? Does the solver crash? Does it hit the maximum number of iterations? Does it report infeasibility?

**Comment by yasseryasaei** [comment]
Hi there again, 
Sorry for the delay, but I was trying to root cause the problem and make a simple example for which I am receiving some unexpected results. The attached zipped folder contains two files: 
1. The file `data.pkl` that contains a simplified set of data that I am working with that can show the issue I have been dealing with
2. The file `osqp_cvxopt_comparison.ipynb` that contains codes for running and making a comparison between `cvxopt` and `osqp`. 

When I run it on my computer, the results coming from the solvers differ significantly (both the optimal variable determined and the corresponding objective value/cost that is minimized).

I also have checked with `cvxpy` backed by `ecos` and the results from that solver is highly consistent with what `cvxopt` delivers.

PS: I have found where the code was crashing inside the loop I was mentioning in the previous communication boxes and have simplified it to the above problem for you to diagnose. 

Thank you,

[osqp_cvxopt_comparison.zip](https://github.com/oxfordcontrol/osqp/files/1835100/osqp_cvxopt_comparison.zip)

**Comment by bstellato** [comment]
It looks like this is related to the scaling of your problem. You can check that `np.linalg.cond(PP_) = 9860981.74`. OSQP internally rescales the problem using a heuristic (as all the other solvers) but this might not always lead to the optimal scaling.

Since OSQP has lower tolerances by default (it is a first-order method),  the reported solution might be far from what CVXOPT reports while still satisfying the termination criteria. However, If you decrease `eps_rel=1e-09`, you should get something much closer than what you need.

I suggest you to play with `eps_rel` and `eps_abs` (you can put both of them to `1e-09`). However, note that the number of iterations can considerably increase and you might need to adjust `max_iter` in case.

Here is the code:

```python
import pandas as pd
import numpy as np
from scipy import sparse
import osqp
import cvxopt

# reading data from a pickle file
df_ = pd.read_pickle(path='data.pkl')
lib_aux = df_['lib'].values[0]
baseload = df_['bl'].values[0]
wf = df_['wf'].values[0]


wf_x = wf - baseload
library = lib_aux

# The commented lines below are for sanity check for the two solvers (simple examples)
# wf_x = np.array([.1, .3, .435, 134])
# library = np.array([[1, 0.4, .234, 3], [0, 1, 22, .23]])

size = library.shape[0]
upper = np.ones(size)
lower = np.zeros(size)

# the following variables will be used in two different ways in the next two cells.
LL_ = library.T
PP_ = np.dot(LL_.T, LL_)
size = PP_.shape[1]
qq_ = np.dot(-LL_.T, wf_x)
GG_ = np.vstack([np.eye(size), -np.eye(size)])
hh_ = np.hstack([upper, -lower]).astype('float')


# Define the minimization problem in osqp format
P_ = sparse.csc_matrix(PP_)
q_ = qq_
A_ = sparse.eye(size, dtype='float').tocsc()
problem = osqp.OSQP()
problem.setup(P=P_, q=q_, A=A_, l=lower, u=upper,
              verbose=True,
              eps_abs=1e-9,
              eps_rel=1e-9)
sol = problem.solve()
if sol.info.status == 'solved':
    opt_var_osqp = sol.x
else:
    raise ValueError("OSQP did not solve the problem")
aux_var = np.dot(LL_, opt_var_osqp) - wf_x
opt_obj_osqp = np.linalg.norm(aux_var, ord=2)


# This cell is to define the minimization problem in cvxopt format
P_ = cvxopt.matrix(PP_)
q_ = cvxopt.matrix(qq_)
G_ = cvxopt.matrix(GG_)
h_ = cvxopt.matrix(hh_)
cvxopt.solvers.options['show_progress'] = False
cvxopt.solvers.options['abstol'] = 1e-10
cvxopt.solvers.options['reltol'] = 1e-9
sol = cvxopt.solvers.qp(P_, q_, G_, h_)
if 'optimal' in sol['status']:
    opt_var_cvx = np.array(sol['x']).reshape((P_.size[1]))
else:
    raise ValueError("CVXOPT did not solve the problem")
aux_var = np.dot(LL_, opt_var_cvx) - wf_x
opt_obj_cvx = np.linalg.norm(aux_var, ord=2)


# comparison of optimal variables derived from the osqp and cvxopt
print("    OSQP\t     CVXOPT\n")
print(np.vstack([opt_var_osqp, opt_var_cvx]).T)
print("\n")

print("Comparison with rounded values\n")
print("   OSQP   CVXOPT\n")
print(np.vstack([np.round(opt_var_osqp, 2), np.round(opt_var_cvx, 2)]).T)
print("\n")

# comparison of optimal objective values derived from the osqp and cvxopt
print("Opt obj CVX = ", opt_obj_cvx)
print("Opt obj OSQP = ", opt_obj_osqp)
```

**Comment by bstellato** [comment]
I am closing this issue since it has been stale for more than a month. Feel free to reopen it in case.
