### ISSUE TITLE
Null pointer dereference in osqp_solve?

### ISSUE THREAD

**Issue by phrack** [oxfordcontrol/osqp#54]
Lines 288 and 291 dereference `work` if `PRINTING` is defined. Just a few lines later on line 302 the code checks to see if `work` is `NULL`. This either suggests `work` cannot be `NULL` or there is a null pointer deference. Since `work` is passed by the caller, this appears to be a possible null pointer dereference.

https://github.com/oxfordcontrol/osqp/blob/88277e9f0a2c7079002bb12356bd5e5363b42042/src/osqp.c#L288
https://github.com/oxfordcontrol/osqp/blob/88277e9f0a2c7079002bb12356bd5e5363b42042/src/osqp.c#L291
https://github.com/oxfordcontrol/osqp/blob/88277e9f0a2c7079002bb12356bd5e5363b42042/src/osqp.c#L302

**Comment by bstellato** [comment]
Thanks for spotting that. `if (!work)` was at the right place before but for some weird reason it ended up after these lines.
