### ISSUE TITLE
matlab install crash v2016a

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/osqp#6]
Running the 'run_osqp_tests.m' scripts crashes in R2016a.

The crash happens during the codegen tests, since the function osqp.codegen expects to get a 'folder' field from the matlab 'dir' command (see osqp.m line 425).   This behaviour of the matlab 'dir' command seems to have been added from R2016b.

**Comment by bstellato** [comment]
Fixed and added to CHANGELOG.md (e07c7477a12fb23db34da6fb0d63afcd1b0a3e8e, e07c7477a12fb23db34da6fb0d63afcd1b0a3e8e)
