### ISSUE TITLE
Number of non-zero hessian elements seems to be non-coherent 

### ISSUE THREAD

**Issue by GiulioRomualdi** [oxfordcontrol/osqp#61]
When an optimization problem is initialized all the data saved in the `OSQPData` struct are copied inside  `OSQPWorkspace` by the way the number of non-zero elements of the hessian matrix seems to be non-coherent.

As regarding the Hessian matrix `P` only its upper-diagonal part is saved by using 
https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/osqp.c#L114
Inside this method the number of non-zero elements is _estimated_ 
https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/cs.c#L259-L266
and then saved 
https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/cs.c#L309-L310

However the numbers of non-zero elements of `data->P` and `work->data->P` seems to be different.   
I wrote a simple test in order to better explain this behaviour [osqp-test.zip](https://github.com/oxfordcontrol/osqp/files/1955257/osqp-test.zip).   
In the following some lines are shown 
```c
// Structures
OSQPWorkspace * work;  // Workspace
OSQPData * data;  // OSQPData

// Populate data
data = (OSQPData *)c_malloc(sizeof(OSQPData));
data->n = n;
data->m = m;
data->P = csc_matrix(data->n, data->n, P_nnz, P_x, P_i, P_p);
data->q = q;
data->A = csc_matrix(data->m, data->n, A_nnz, A_x, A_i, A_p);
data->l = l;
data->u = u;

// Define Solver settings as default
osqp_set_default_settings(settings);

settings->alpha = 1.0; // Change alpha parameter

// Setup workspace
work = osqp_setup(data, settings);
printf("#nonzero elements (original) %lld\n", data->P->nzmax);
printf("#nonzero elements (inside workspace) %lld\n", work->data->P->nzmax);
```
The output is  
```
-----------------------------------------------------------------
           OSQP v0.3.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2017
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 3
          nnz(P) + nnz(A) = 8
settings: linear system solver = suitesparse ldl,
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.00, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off

#nonzero elements (original) 2
#nonzero elements (inside workspace) 4
```

Is this  behaviour desired? Is it a bug? If it's a bug I think it can be easily solved by changing this line
https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/cs.c#L309-L310
into 
```c
M_triu->nzmax = z_M; 
```

**Comment by bstellato** [comment]
The behavior is correct. Here are a few comments to make it more clear

- We extract only the upper triangular part of `P` whether or not we pass the full `P` or the upper triangular part of `P`.  Thus, the number of nonzero elements can be can change in the conversion.

- `nnzmax` is just the maximum possible number of nonzero elements in the matrix. It does not always correspond to the number of nonzero elements. To get the number of nonzero elements I suggest you to look at the last elements of the `P->p` array. If you change your code as follows:

    ```c
        printf("#nonzero elements (original) %lld\n", data->P->p[data->P->n]);
        printf("#nonzero elements (inside workspace) %lld\n", work->data->P->p[work->data->P->n]);
    ```

    it should return the correct answer. Not that this happens only because your matrix `P` is  upper 
    triangular (in this case diagonal). If you pass a full matrix, the result can be different.

- If the matrix is in triplet format, the number of nonzeros is stored in `nz`. This is described in 

  
  https://github.com/oxfordcontrol/osqp/blob/08bdea451f9c31ef1ec46506f2c9211a01c12cd0/include/types.h#L19-L29

    this is why we assign it here. 
  
  https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/cs.c#L303-L305

    Afterwards, the conversion

  
  https://github.com/oxfordcontrol/osqp/blob/71aaadb3daad3ae133400d1d0b73f1644cd21ae9/src/cs.c#L306-L308

    assigns the right matrix.

Hope it is a bit more clear now.

**Comment by GiulioRomualdi** [comment]
Yes! thank you very much!

**Comment by bstellato** [comment]
Great! I will close the issue. Feel free to reopen it if it is still unclear.
