### ISSUE TITLE
matlab codegen crash for unscaled problems

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/osqp#7]
Matlab crashes when calling `osqp.codegen()` if user sets 

> settings.scaling = 0.

The crash occurs in the call to `osqp_mex('get_workspace')`

## Example 

```matlab
%small problem
P = sparse([4., 1.; 1., 2.]);
q = [1; 1];
A = sparse([1., 1; 1, 0; 0, 1]);
l = [1.0; 0.0; 0.0];
u = [1.0; 0.7; 0.7];

%1 = ok, 0 = crash
settings.scaling = 0;

% Solve with osqp and export
solver = osqp;
solver.setup(P, q, A, l, u, settings);
solver.solve();

%crashes here
solver.codegen('export', 'project_type','Xcode','parameters', 'matrices', 'mexname', 'emosqp');
```

**Comment by bstellato** [comment]
When `scaling` is disabled, the scaling structure is not allocated. The workspace renderer was trying to access the `scaling` variables even when they did not exist causing the crash in both Python and Matlab.

It is now fixed af59e254febababd8cca60f752e68bf4c00c470a
