### ISSUE TITLE
MemoryError when the dimention is too large

### ISSUE THREAD

**Issue by lith0613** [oxfordcontrol/osqp#73]
I have to solve a QP problem with all dimension between zero and one , in order to use the OSQP solver, so I change them into the linear inequality form constraints ,maybe the vector dimention is too large ,more than 200000 ,then in numpy prompted MemoryError

**Comment by gbanjac** [comment]
Could you please provide a MWE in which you get the error?

**Comment by lith0613** [comment]
P = sparse.csc_matrix(H)
E = np.vstack([H, Aeq])
E = sparse.csc_matrix(E)
l =  np.vstack([lb, beq])
u = np.vstack([ub, beq])
prob = osqp.OSQP()
prob.setup(self.P, self.q, self.E, self.l, self.u, alpha=1.0, verbose=False)

my demo code is above
the error is below:

  File "/home/lth/myProject/cnn/mul_layer.py", line 68, in __init__
    P=sparse.csc_matrix(np.eye(N))
 File "/home/lth/anaconda3/lib/python3.5/site-packages/numpy/lib/twodim_base.py", line 186, in eye
    m = zeros((N, M), dtype=dtype, order=order)

MemoryError

**Comment by gbanjac** [comment]
I am sorry, but this is not a minimum working example. You should provide code that someone else could run. You have not provided all the information required.

However, it seems from the error code above that the error does not occur with OSQP, but with NumPy. How big is your `N`? You might consider setting `P` as `P=sparse.eye(N).tocsc()`.

**Comment by lith0613** [comment]
I am sorry , this is my demo code:

import numpy as np
import random

import time

def tic():
    globals()['tt'] = time.clock()

def toc():
    print ('\nElapsed time: %.8f seconds\n' % (time.clock()-globals()['tt']))


N=100000
k=100
v_index=random.sample(range(0,N),k)  #minimal:0  maximal:N-1  sample:k
v = np.zeros([N,1])  
v[v_index,0]=1  
y1 = np.zeros([N,1]) 
f=-v-y1
H=np.eye(N)

lb=np.zeros([N,1])
ub=np.ones([N,1])

Aeq=np.ones([N,1]).transpose()
beq=k*np.ones([1,1])


'''osqp'''
import osqp
import scipy.sparse as sparse

# Define problem data
P = sparse.csc_matrix(H)
q = f
A = np.vstack([H, Aeq])
A = sparse.csc_matrix(A)
l = np.vstack([lb, beq])
u = np.vstack([ub, beq])


# Create an OSQP object
tic()
prob = osqp.OSQP()
toc()

tic()
# Setup workspace and change alpha parameter
prob.setup(P, q, A, l, u, alpha=1.0)

# Solve problem
res = prob.solve()
toc()
z3=res.x
print(z3.shape)

**Comment by gbanjac** [comment]
I just edited few lines of your code and it seems to work now. The code is shown below:
```
import numpy as np
import random

import time

def tic():
  globals()['tt'] = time.clock()

def toc():
  print ('\nElapsed time: %.8f seconds\n' % (time.clock()-globals()['tt']))

N=100000
k=100
v_index=random.sample(range(0,N),k) #minimal:0 maximal:N-1 sample:k
v = np.zeros([N,1])
v[v_index,0]=1
y1 = np.zeros([N,1])
f=-v-y1
#H=np.eye(N)                          # COMMENTED OUT

lb=np.zeros([N,1])
ub=np.ones([N,1])

Aeq=np.ones([N,1]).transpose()
beq=k*np.ones([1,1])

import osqp
import scipy.sparse as sparse

P = sparse.eye(N).tocsc()             # MODIFIED
q = f
A = sparse.vstack([P, Aeq]).tocsc()   # MODIFIED
#A = sparse.csc_matrix(A)             # COMMENTED OUT
l = np.vstack([lb, beq])
u = np.vstack([ub, beq])

tic()
prob = osqp.OSQP()
toc()

tic()
prob.setup(P, q, A, l, u, alpha=1.0)
res = prob.solve()
toc()
z3=res.x
print(z3.shape)
```
The problem was not related to OSQP. The error occurred when you tried to construct a dense matrix `H` with `1e10` elements. This can be avoided by using sparse matrices instead.

**Comment by lith0613** [comment]
Thank you so much ! 
I will have a try.

**Comment by gbanjac** [comment]
I will close the issue. Feel free to reopen it if you still have some problems.
