### ISSUE TITLE
osqp matlab interface true/false options

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/osqp#8]
The osqp.m interface does not allow true/false values as settings.  For example, it insists on 

```
>> options.polish = 0;
```

instead of allowing also

```
>> options.polish = false;
```

**Comment by bstellato** [comment]
It should be resolved in this commit: 0e054e32ea5885f5c1aa54655fc773af4cbe405f

Let me know if it works now.

**Comment by goulart-paul** [comment]
Yes, it works now.
