### ISSUE TITLE
How to include osqp in a CMake project

### ISSUE THREAD

**Issue by mcamurri** [oxfordcontrol/osqp#88]
Hi all,
this might be a basic question.

I've just built and installed `osqp` from source and I want to include it in a custom CMake project:
```
cmake_minimum_required(VERSION 2.8)

project(osqp_test)
find_package(osqp)

if(${osqp_FOUND})
    message(STATUS "Found osqp")
endif

add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} ${osqp_LIBRARIES})
```
When I run `find_package` the library is correctly found, but the standard CMake variables such as `oscp_INCLUDE_DIRS` or `osqp_LIBRARIES are not created.

The only variables defined are:
```
-- osqp_CONFIG=/usr/local/lib/cmake/osqp/osqp-config.cmake
-- osqp_CONSIDERED_CONFIGS=/usr/local/lib/cmake/osqp/osqp-config.cmake
-- osqp_CONSIDERED_VERSIONS=unknown
-- osqp_DIR=/usr/local/lib/cmake/osqp
-- osqp_FOUND=1
-- osqp_VERSION_COUNT=0
-- osqp_VERSION_MAJOR=0
-- osqp_VERSION_MINOR=0
-- osqp_VERSION_PATCH=0
-- osqp_VERSION_TWEAK=0
-- osqp_test_BINARY_DIR=/home/mcamurri/build-osqp-Desktop-Default
-- osqp_test_SOURCE_DIR=/home/mcamurri/osqp
```
Where  the `INCLUDE_DIRS` and `LIBRARIES` CMake variables are defined?

**Comment by bstellato** [comment]
The cmake package addition should be working with the `target_link_libraries` command. That's what has been added in https://github.com/oxfordcontrol/osqp/pull/41. There are a few links in that description about how to add OSQP with cmake. Do you have issues or errors with it?

**Comment by mcamurri** [comment]
[PkgConfig](https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html) normally produces variables like `oscp_INCLUDE_DIRS` or `osqp_LIBRARIES`

I thought this was standard also for the plain `find_package()` cmake command, but looking into the official doc it seems not (maybe it was in the past).

I have no issues in doing as #41 suggest so I close the issue.

Sorry for bothering.
