### ISSUE TITLE
Provide dense matrix interface for QP problems.

### ISSUE THREAD

**Issue by lianglia-apollo** [oxfordcontrol/osqp#95]
Is it possible to provide dense matrix interface for QP problems.

**Comment by bstellato** [comment]
It is almost never a good idea to pass a dense problem to a sparse solver. Which problem type are you solving? Most real world problems are sparse. 

Which interface are you using? If you are using high level languages such as python, julia or matlab they sparsify the matrices for you.

**Comment by lianglia-apollo** [comment]
Although the final result is sparse, it sometimes come from dense matrix operations. A wrapper interface for dense matrix is useful for those applications.

I am using c++, but the license of sparse matrix package is not the same as osqp. It put some limits to the application.
