### ISSUE TITLE
Primal feasibility guarantee?

### ISSUE THREAD

**Issue by qnzhou** [oxfordcontrol/osqp#97]
Hi there,

Thanks for providing this awesome library.  I have more of a theoretical question: does OSQP (or ADMM in general) guarantees primal feasibility with finite amount of iterations?

I notice that [the paper](http://web.stanford.edu/~boyd/papers/pdf/admm_distr_stats.pdf) provides proof for primal and dual feasibility in the limit of infinite number of iterations.  However, I found that the solution returned by OSQP always has a non-zero primal residual.  If I _really really_ need to find a solution within the feasible region, is it possible to achieve that with OSQP (or ADMM in general)?

**Comment by goulart-paul** [comment]
The short answer is no, ADMM is not guaranteed to converge to a feasible point in a finite number of iterations.

However, within the OSQP solver itself things are bit better.   If you have polishing enabled, then after the solver reaches its convergence tolerance it will make a guess at the correct active set and try to compute a high precision solution while treating that active set as a collection of equality constraints.

If this is successful, then the solver will return the ‘polished’ solution and it will be very accurate (and primal feasible).




On 7 Oct 2018, at 23:15, Qingnan Zhou <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

Thanks for providing this awesome library. I have more of a theoretical questions: does OSQP (or ADMM in general) guarantees primal feasibility with finite amount of iterations?

I notice that the paper<http://web.stanford.edu/%7Eboyd/papers/pdf/admm_distr_stats.pdf> provides proof for primal and dual feasibility in the limit of infinite number of iterations. However, I found that the solution returned by OSQP always has a non-zero primal residual. If I really really need to find a solution within the feasible region, is it possible to achieve that with OSQP (or ADMM in general)?

**Comment by qnzhou** [comment]
Thanks @goulart-paul for the quick answer!  Unfortunately, polishing is not successful in my case...

**Comment by goulart-paul** [comment]
If it is not successful then it means that the solver is either not getting to the correct active set, or that your problem is actually infeasible.

You could try tightening the termination tolerances to ensure you are closer to optimality before attempting to polish.   You may need to also increase the allowable number of iterations if you do this, since convergence to high accuracy is not always that fast.


On 7 Oct 2018, at 23:50, Qingnan Zhou <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @goulart-paul<https://github.com/goulart-paul> for the quick answer! Unfortunately, polishing is not successful in my case...

**Comment by bstellato** [comment]
A few comments:

* the same issue appears with interior-point methods where the residuals converge to zero in the limit.
 
* Primal dual feasibility are controlled using the `rho` parameter. To get primal feasibility satisfied as quickly as possible (ignoring optimality) I suggest you to decrease `rho` and remove the `auto` option.  I would also change the primal/dual feasibility tolerances accordingly. You might get very suboptimal solutions this way.

* The polishing step works better then the tolerances are small (sometimes `1e-05` or `1e-08`). This also requires many more iterations though. 

* Primal active set methods could be an alternative to get what you need. They aim at dual feasibility and complementary slackness in the limit while satisfying primal feasibility.  However they do not tend to work well for large QPs/LPs with many constraints.  Our method instead always satisfies complementary slackness while aiming at primal and dual feasibility in the limit. How large is your problem?

**Comment by qnzhou** [comment]
Thanks for the suggestions.  My pursuit for feasibility is unfortunately not successful.  First of all, the problem I am solving has theoretical guarantee on feasibility, and I am able to validate that in my implementation by constructing a feasible point.

I am testing on simple toy problems for now.  My setup consists of 209 variables and 288 constraints.  I should probably mention that some of the constraint are equality constraints (enforced by setting `l[i] == u[i]`), and I set `P == 0` (i.e. linear programming) to remove confounding factors.

Here is my settings:

```python
solver.setup(P, q, A, l, u,
            verbose=True,
            polish=True,
            eps_prim_inf=0,
            eps_dual_inf=0,
            eps_abs=5e-10,
            eps_rel=1e-12, 
            max_iter=1e7,
            polish_refine_iter=1e7,
            rho=1e-12,
            adaptive_rho_fraction=1.0);   
```

I was only able to reduce primal residual to around 5e-10.  After that the residual value will only fluctuate around but not decrease further.   Even with residual this small, the polishing step has not been successful so far.  It is possible the above setting contains obvious mistakes.  Any hint is appreciated.

**Comment by gbanjac** [comment]
A few comments from my side:

- It is not advised to set tolerances `eps_prim_inf` and `eps_dual_inf` to zero. This would mean that your infeasibility checks will never be satisfied.

- There is no need to perform `1e7` iterative refinement iterations. The default value for `polish_refine_iter` is set to 3 which is almost always sufficient. You may consider taking 5 or 10 steps, but 10 million steps is not what you want.

- Polishing will typically succeed only if both primal and dual residuals are small enough.

- If having primal residual being `1e-10` is not sufficiently small for your application, then you are probably doing something wrong. Which accuracy do you hope for?

**Comment by qnzhou** [comment]
Thanks again for the help and suggestions.  Both primal and dual residual are of similar magnitude (around `5e-10`).  It is certainly small enough.  :)  The only unsatisfactory point is that I was not able to get the polishing step to work no matter how small the residuals are.

I am closing this issue as it is getting beyond my original question.  Thanks so much for the discussion!

**Comment by bstellato** [comment]
Feel free to send us your QP data if you would like us to try to get polishing to work. We are slowly collecting [problems](https://github.com/oxfordcontrol/osqp_problems_collection) where the convergence is problematic.
